// Chusky credential broker. Credentials enter only through the one-time form,
// stay encrypted in D1, and are released over an authenticated HTTPS call only
// to the trusted Chusky runtime for direct Daytona injection.

interface Env { VAULT_DB: D1Database; VAULT_MASTER_KEY: string; BROKER_HMAC_SECRET: string; }
type Json = Record<string, unknown>;
const MAX_BODY = 16_384;
const TICKET_TTL_MS = 10 * 60_000;
const REQUEST_SKEW_MS = 60_000;
const SESSION_STATES = new Set(["authenticated", "unknown", "expired", "logged_out", "needs_reauth", "awaiting_user_interaction"]);

function json(value: Json, status = 200): Response { return new Response(JSON.stringify(value), { status, headers: { "content-type": "application/json; charset=utf-8", "cache-control": "no-store", "x-content-type-options": "nosniff" } }); }
function html(body: string, status = 200): Response { return new Response(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; form-action 'self'; base-uri 'none'; frame-ancestors 'none'"><title>Chusky secure login</title><style>body{font:16px system-ui,sans-serif;background:#10131a;color:#f3f5f7;margin:0;padding:32px}.card{max-width:440px;margin:auto;background:#1a2030;padding:28px;border-radius:16px}label{display:block;margin:16px 0 6px}input{box-sizing:border-box;width:100%;padding:12px;border-radius:8px;border:1px solid #59637a;background:#0d111b;color:#fff}button{margin-top:22px;width:100%;padding:12px;border:0;border-radius:8px;background:#5294ff;color:#061225;font-weight:700}.note{color:#b9c4da;font-size:.9rem;line-height:1.45}</style></head><body><main class="card">${body}</main></body></html>`, { status, headers: { "content-type": "text/html; charset=utf-8", "cache-control": "no-store", "referrer-policy": "no-referrer", "x-content-type-options": "nosniff" } }); }
function escape(value: string): string { return value.replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!); }
function b64(bytes: Uint8Array): string { let out = ""; for (const byte of bytes) out += String.fromCharCode(byte); return btoa(out).replaceAll("+", "-").replaceAll("/", "_").replace(/=+$/g, ""); }
function unb64(value: string): Uint8Array { const padded = value.replaceAll("-", "+").replaceAll("_", "/") + "===".slice((value.length + 3) % 4); const raw = atob(padded); return Uint8Array.from(raw, (char) => char.charCodeAt(0)); }
function random(size: number): Uint8Array { const out = new Uint8Array(size); crypto.getRandomValues(out); return out; }
function now(): number { return Date.now(); }
function requireString(value: unknown, field: string, max: number): string { if (typeof value !== "string" || !value.trim() || value.trim().length > max) throw new Error(`${field} is invalid`); return value.trim(); }
function service(value: unknown): string { const result = requireString(value, "service", 80).toLowerCase(); if (!/^[a-z0-9][a-z0-9 ._-]*$/.test(result)) throw new Error("service is invalid"); return result; }
function account(value: unknown): string { const result = requireString(value, "accountId", 100); if (!/^account_\d{1,20}$/.test(result)) throw new Error("accountId is invalid"); return result; }
function origin(value: unknown): string { const url = new URL(requireString(value, "origin", 300)); if (url.protocol !== "https:" || url.username || url.password || url.pathname !== "/" || url.search || url.hash) throw new Error("origin is invalid"); return url.origin; }
function ownUrl(value: unknown, base: string, field: string): string { const url = new URL(typeof value === "string" && value ? value : base, base); if (url.protocol !== "https:" || url.origin !== base || url.username || url.password) throw new Error(`${field} is invalid`); return url.toString(); }
async function sha256(value: string): Promise<string> { return b64(new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)))); }
async function hmac(secret: string, value: string): Promise<Uint8Array> { const key = await crypto.subtle.importKey("raw", new TextEncoder().encode(secret), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]); return new Uint8Array(await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(value))); }
function same(a: Uint8Array, b: Uint8Array): boolean { if (a.byteLength !== b.byteLength) return false; let diff = 0; for (let i = 0; i < a.byteLength; i += 1) diff |= a[i]! ^ b[i]!; return diff === 0; }
async function readJson(request: Request): Promise<Json> { const length = Number(request.headers.get("content-length") || 0); if (length > MAX_BODY) throw new Error("request too large"); const text = await request.text(); if (text.length > MAX_BODY) throw new Error("request too large"); const body = JSON.parse(text || "{}") as unknown; if (!body || typeof body !== "object" || Array.isArray(body)) throw new Error("invalid request"); return body as Json; }
async function encrypted(master: string, value: Json) {
  const masterKey = await crypto.subtle.importKey("raw", unb64(master), { name: "AES-GCM" }, false, ["encrypt", "decrypt"]);
  const dek = random(32); const dataIv = random(12); const dekIv = random(12); const dataKey = await crypto.subtle.importKey("raw", dek, { name: "AES-GCM" }, false, ["encrypt", "decrypt"]);
  const payload = new TextEncoder().encode(JSON.stringify(value)); const data = new Uint8Array(await crypto.subtle.encrypt({ name: "AES-GCM", iv: dataIv }, dataKey, payload)); const wrapped = new Uint8Array(await crypto.subtle.encrypt({ name: "AES-GCM", iv: dekIv }, masterKey, dek));
  return { ciphertext: b64(data.slice(0, -16)), dataIv: b64(dataIv), dataTag: b64(data.slice(-16)), wrappedDek: b64(wrapped.slice(0, -16)), dekIv: b64(dekIv), dekTag: b64(wrapped.slice(-16)) };
}
async function decrypted(master: string, row: Record<string, unknown>): Promise<{ username: string; password: string }> {
  const masterKey = await crypto.subtle.importKey("raw", unb64(master), { name: "AES-GCM" }, false, ["decrypt"]); const wrapped = new Uint8Array([...unb64(String(row.wrapped_dek)), ...unb64(String(row.dek_tag))]);
  const dek = await crypto.subtle.decrypt({ name: "AES-GCM", iv: unb64(String(row.dek_iv)) }, masterKey, wrapped); const dataKey = await crypto.subtle.importKey("raw", dek, { name: "AES-GCM" }, false, ["decrypt"]); const data = new Uint8Array([...unb64(String(row.ciphertext)), ...unb64(String(row.data_tag))]);
  const value = JSON.parse(new TextDecoder().decode(await crypto.subtle.decrypt({ name: "AES-GCM", iv: unb64(String(row.data_iv)) }, dataKey, data))) as Json;
  return { username: requireString(value.username, "credential", 500), password: requireString(value.password, "credential", 2000) };
}
async function audit(env: Env, accountId: string, event: string, requestId: string, metadata: Json = {}, credentialId?: string, identityId?: string): Promise<void> { await env.VAULT_DB.prepare("INSERT INTO vault_audit_log (id,account_hash,event,credential_id,identity_id,request_id,metadata_json,created_at) VALUES (?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(), await sha256(accountId), event, credentialId || null, identityId || null, requestId, JSON.stringify(metadata), now()).run(); }
async function authenticated(request: Request, env: Env, path: string, body: string): Promise<{ requestId: string }> {
  const timestamp = request.headers.get("x-chusky-timestamp") || ""; const nonce = request.headers.get("x-chusky-nonce") || ""; const supplied = request.headers.get("x-chusky-signature") || ""; const requestId = request.headers.get("x-chusky-request-id") || crypto.randomUUID();
  if (!/^\d{13}$/.test(timestamp) || !/^[0-9a-f-]{36}$/i.test(nonce) || Math.abs(now() - Number(timestamp)) > REQUEST_SKEW_MS) throw new Error("unauthorized");
  const expected = await hmac(env.BROKER_HMAC_SECRET, `POST\n${path}\n${timestamp}\n${nonce}\n${await sha256(body)}`); if (!same(expected, unb64(supplied))) throw new Error("unauthorized");
  const nonceHash = await sha256(nonce); const expiry = now() + REQUEST_SKEW_MS;
  const claim = await env.VAULT_DB.prepare("INSERT OR IGNORE INTO vault_broker_nonces (nonce_hash,expires_at) VALUES (?,?)").bind(nonceHash, expiry).run();
  if (!claim.meta.changes) throw new Error("replayed request");
  return { requestId };
}
async function broker(request: Request, env: Env): Promise<Response> {
  const url = new URL(request.url); const raw = await request.text(); let body: Json;
  try { if (raw.length > MAX_BODY) throw new Error("request too large"); body = JSON.parse(raw || "{}") as Json; } catch { return json({ error: "invalid request" }, 400); }
  let auth: { requestId: string }; try { auth = await authenticated(request, env, url.pathname, raw); } catch { return json({ error: "unauthorized" }, 401); }
  try {
    const accountId = account(body.accountId);
    if (url.pathname === "/v1/setup") {
      const site = service(body.service); const siteOrigin = origin(body.origin); const created = now(); const token = b64(random(32)); const id = crypto.randomUUID(); const expiresAt = created + TICKET_TTL_MS;
      const loginUrl = ownUrl(body.loginUrl, siteOrigin, "loginUrl"); const logoutUrl = body.logoutUrl ? ownUrl(body.logoutUrl, siteOrigin, "logoutUrl") : null;
      const usernameFieldLabel = requireString(body.usernameFieldLabel || "Email or username", "usernameFieldLabel", 120); const passwordFieldLabel = requireString(body.passwordFieldLabel || "Password", "passwordFieldLabel", 120); const submitButtonLabel = requireString(body.submitButtonLabel || "Sign in", "submitButtonLabel", 120);
      await env.VAULT_DB.prepare("INSERT INTO vault_setup_tickets (id,token_hash,account_id,service,origin,login_url,logout_url,username_field_label,password_field_label,submit_button_label,expires_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)").bind(id, await sha256(token), accountId, site, siteOrigin, loginUrl, logoutUrl, usernameFieldLabel, passwordFieldLabel, submitButtonLabel, expiresAt).run();
      await audit(env, accountId, "setup_started", auth.requestId, { service: site }); return json({ service: site, origin: siteOrigin, expiresAt, setupUrl: `${url.origin}/setup/${id}?token=${encodeURIComponent(token)}` });
    }
    if (url.pathname === "/v1/list") {
      const rows = await env.VAULT_DB.prepare("SELECT c.id,c.service,c.origin,c.login_url,i.id AS identity_id,i.workspace_id,i.status,i.last_authenticated_at,i.last_used_at,i.expires_at FROM vault_credentials c LEFT JOIN vault_browser_identities i ON i.credential_id=c.id AND i.account_id=c.account_id WHERE c.account_id=? AND c.status='active' ORDER BY c.updated_at DESC").bind(accountId).all<Record<string, unknown>>();
      const credentials = rows.results.map((row) => ({ id: String(row.id), service: String(row.service), origin: String(row.origin), loginUrl: String(row.login_url), session: row.identity_id ? { id: String(row.identity_id), service: String(row.service), origin: String(row.origin), workspaceId: String(row.workspace_id), status: String(row.status), lastAuthenticatedAt: row.last_authenticated_at || undefined, lastUsedAt: row.last_used_at || undefined, expiresAt: row.expires_at || undefined } : undefined }));
      await audit(env, accountId, "credential_listed", auth.requestId, { count: credentials.length }); return json({ credentials });
    }
    if (url.pathname === "/v1/status") {
      const queryService = body.service ? service(body.service) : undefined; const statement = queryService ? env.VAULT_DB.prepare("SELECT i.id,c.service,i.origin,i.workspace_id,i.status,i.last_authenticated_at,i.last_used_at,i.expires_at FROM vault_browser_identities i JOIN vault_credentials c ON c.id=i.credential_id WHERE i.account_id=? AND c.service=? ORDER BY i.updated_at DESC").bind(accountId, queryService) : env.VAULT_DB.prepare("SELECT i.id,c.service,i.origin,i.workspace_id,i.status,i.last_authenticated_at,i.last_used_at,i.expires_at FROM vault_browser_identities i JOIN vault_credentials c ON c.id=i.credential_id WHERE i.account_id=? ORDER BY i.updated_at DESC").bind(accountId);
      const result = await statement.all<Record<string, unknown>>(); const sessions = result.results.map((row) => ({ id: String(row.id), service: String(row.service), origin: String(row.origin), workspaceId: String(row.workspace_id), status: String(row.status), lastAuthenticatedAt: row.last_authenticated_at || undefined, lastUsedAt: row.last_used_at || undefined, expiresAt: row.expires_at || undefined }));
      await audit(env, accountId, "session_checked", auth.requestId, { count: sessions.length }); return json({ sessions });
    }
    if (url.pathname === "/v1/lease") {
      const site = service(body.service); const row = await env.VAULT_DB.prepare("SELECT * FROM vault_credentials WHERE account_id=? AND service=? AND status='active'").bind(accountId, site).first<Record<string, unknown>>(); if (!row) return json({ error: "credential not found" }, 404);
      const secret = await decrypted(env.VAULT_MASTER_KEY, row); await env.VAULT_DB.prepare("UPDATE vault_credentials SET last_used_at=? WHERE id=?").bind(now(), row.id).run(); await audit(env, accountId, "credential_leased", auth.requestId, { service: site }, String(row.id));
      return json({ credential: { id: row.id, service: row.service, origin: row.origin, loginUrl: row.login_url, usernameFieldLabel: row.username_field_label, passwordFieldLabel: row.password_field_label, submitButtonLabel: row.submit_button_label, ...secret } });
    }
    if (url.pathname === "/v1/session") {
      const credentialId = requireString(body.credentialId, "credentialId", 100); const workspaceId = requireString(body.workspaceId, "workspaceId", 200); const sessionOrigin = origin(body.origin); const state = requireString(body.status, "status", 80); if (!SESSION_STATES.has(state)) throw new Error("status is invalid"); const id = crypto.randomUUID(); const updated = now();
      const credential = await env.VAULT_DB.prepare("SELECT id,service FROM vault_credentials WHERE id=? AND account_id=? AND status='active'").bind(credentialId, accountId).first<Record<string, unknown>>(); if (!credential) return json({ error: "credential not found" }, 404);
      await env.VAULT_DB.prepare("INSERT INTO vault_browser_identities (id,account_id,credential_id,workspace_id,origin,status,last_authenticated_at,last_used_at,expires_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(account_id,credential_id,workspace_id) DO UPDATE SET origin=excluded.origin,status=excluded.status,last_authenticated_at=excluded.last_authenticated_at,last_used_at=excluded.last_used_at,expires_at=excluded.expires_at,updated_at=excluded.updated_at").bind(id, accountId, credentialId, workspaceId, sessionOrigin, state, body.lastAuthenticatedAt || null, body.lastUsedAt || null, body.expiresAt || null, updated, updated).run();
      const session = await env.VAULT_DB.prepare("SELECT id,workspace_id,status,last_authenticated_at,last_used_at,expires_at FROM vault_browser_identities WHERE account_id=? AND credential_id=? AND workspace_id=?").bind(accountId, credentialId, workspaceId).first<Record<string, unknown>>(); await audit(env, accountId, "session_updated", auth.requestId, { service: credential.service, status: state }, credentialId, String(session!.id));
      return json({ session: { id: session!.id, service: credential.service, origin: sessionOrigin, workspaceId: session!.workspace_id, status: session!.status, lastAuthenticatedAt: session!.last_authenticated_at || undefined, lastUsedAt: session!.last_used_at || undefined, expiresAt: session!.expires_at || undefined } });
    }
    if (url.pathname === "/v1/logout") { const site = service(body.service); await env.VAULT_DB.prepare("UPDATE vault_browser_identities SET status='logged_out',updated_at=? WHERE account_id=? AND credential_id IN (SELECT id FROM vault_credentials WHERE account_id=? AND service=?)").bind(now(), accountId, accountId, site).run(); await audit(env, accountId, "session_logged_out", auth.requestId, { service: site }); return json({ service: site, status: "logged_out", note: "Chusky will no longer reuse the saved browser session. The encrypted login remains saved." }); }
    return json({ error: "not found" }, 404);
  } catch (error) { console.warn(JSON.stringify({ event: "vault_broker_error", path: url.pathname, requestId: auth.requestId, error: error instanceof Error ? error.message : "unknown" })); return json({ error: "vault broker request could not be completed" }, 400); }
}
async function setupForm(request: Request, env: Env): Promise<Response> { const url = new URL(request.url); const id = url.pathname.split("/").pop() || ""; const token = url.searchParams.get("token") || ""; if (!id || !token) return html("<h1>Invalid setup link</h1><p>Request a new private link from Chusky.</p>", 400); return html(`<h1>Connect a website</h1><p class="note">Your login is encrypted in Chusky's credential broker. It is not visible to Chusky's model, chat, logs, or browser screenshots.</p><form method="post" action="/setup/${encodeURIComponent(id)}"><input type="hidden" name="token" value="${escape(token)}"><label>Username or email<input name="username" autocomplete="username" required maxlength="500"></label><label>Password<input type="password" name="password" autocomplete="current-password" required maxlength="2000"></label><button type="submit">Save encrypted login</button></form><p class="note">This private link expires in 10 minutes and works once.</p>`); }
async function setupSubmit(request: Request, env: Env): Promise<Response> { const id = new URL(request.url).pathname.split("/").pop() || ""; const form = await request.formData(); const token = form.get("token"); const username = form.get("username"); const password = form.get("password"); if (typeof token !== "string" || typeof username !== "string" || typeof password !== "string") return html("<h1>Could not save login</h1><p>Request a new private link from Chusky.</p>", 400); const ticket = await env.VAULT_DB.prepare("UPDATE vault_setup_tickets SET used_at=? WHERE id=? AND token_hash=? AND used_at IS NULL AND expires_at>? RETURNING *").bind(now(), id, await sha256(token), now()).first<Record<string, unknown>>(); if (!ticket) return html("<h1>This link has expired</h1><p>Request a new private link from Chusky.</p>", 400); try { const sealed = await encrypted(env.VAULT_MASTER_KEY, { username: requireString(username, "username", 500), password: requireString(password, "password", 2000) }); const credentialId = crypto.randomUUID(); const timestamp = now(); await env.VAULT_DB.prepare("INSERT INTO vault_credentials (id,account_id,service,origin,login_url,logout_url,username_field_label,password_field_label,submit_button_label,ciphertext,data_iv,data_tag,wrapped_dek,dek_iv,dek_tag,key_version,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(account_id,service) DO UPDATE SET origin=excluded.origin,login_url=excluded.login_url,logout_url=excluded.logout_url,username_field_label=excluded.username_field_label,password_field_label=excluded.password_field_label,submit_button_label=excluded.submit_button_label,ciphertext=excluded.ciphertext,data_iv=excluded.data_iv,data_tag=excluded.data_tag,wrapped_dek=excluded.wrapped_dek,dek_iv=excluded.dek_iv,dek_tag=excluded.dek_tag,updated_at=excluded.updated_at,status='active'").bind(credentialId,ticket.account_id,ticket.service,ticket.origin,ticket.login_url,ticket.logout_url,ticket.username_field_label,ticket.password_field_label,ticket.submit_button_label,sealed.ciphertext,sealed.dataIv,sealed.dataTag,sealed.wrappedDek,sealed.dekIv,sealed.dekTag,1,"active",timestamp,timestamp).run(); await audit(env, String(ticket.account_id), "credential_saved", crypto.randomUUID(), { service: String(ticket.service) }); return html(`<h1>Website connected</h1><p><strong>${escape(String(ticket.service))}</strong> is encrypted and ready for Chusky's trusted Daytona login.</p><p class="note">Return to your private Chusky chat. This link cannot be used again.</p>`); } catch { return html("<h1>Could not save login</h1><p>Request a new private link from Chusky.</p>", 400); } }

export default { async fetch(request: Request, env: Env): Promise<Response> { const path = new URL(request.url).pathname; if (request.method === "GET" && path.startsWith("/setup/")) return setupForm(request, env); if (request.method === "POST" && path.startsWith("/setup/")) return setupSubmit(request, env); if (request.method === "POST" && path.startsWith("/v1/")) return broker(request, env); if (request.method === "GET" && path === "/health") return json({ ok: true, service: "chusky-vault-broker" }); return json({ error: "not found" }, 404); } };
