/**
 * Live end-to-end test for the guarded artifact builders.
 *
 * It uses an isolated synthetic owner, keeps the remote files in Daytona under
 * workspace/live-artifact-smoke, and downloads copies into workspace/ locally.
 * It deliberately never deletes either set so results can be inspected.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { randomUUID } from "node:crypto";
import { deflateSync } from "node:zlib";
import { initStore } from "../src/store.js";
import { DaytonaEngine } from "../src/lib/daytona/engine.js";

const syntheticUserId = 9_998_123_451;
const runId = `live-${new Date().toISOString().replace(/[:.]/g, "-")}-${randomUUID().slice(0, 8)}`;
const remoteBase = `workspace/live-artifact-smoke/${runId}`;
const localBase = join(process.cwd(), "workspace", "live-artifact-smoke", runId);
// A standards-valid 1×1 PNG built locally so ReportLab/Pillow exercises the
// exact same image path as an uploaded company logo without a brittle fixture.
function crc32(bytes: Buffer): number {
  let crc = 0xffffffff;
  for (const byte of bytes) {
    crc ^= byte;
    for (let bit = 0; bit < 8; bit++) crc = (crc >>> 1) ^ (crc & 1 ? 0xedb88320 : 0);
  }
  return (crc ^ 0xffffffff) >>> 0;
}

function pngChunk(type: string, data: Buffer): Buffer {
  const typeBytes = Buffer.from(type, "ascii");
  const length = Buffer.alloc(4); length.writeUInt32BE(data.length);
  const crc = Buffer.alloc(4); crc.writeUInt32BE(crc32(Buffer.concat([typeBytes, data])));
  return Buffer.concat([length, typeBytes, data, crc]);
}

function testLogo(): Buffer {
  const header = Buffer.alloc(13); header.writeUInt32BE(1, 0); header.writeUInt32BE(1, 4); header[8] = 8; header[9] = 6;
  return Buffer.concat([Buffer.from("89504e470d0a1a0a", "hex"), pngChunk("IHDR", header), pngChunk("IDAT", deflateSync(Buffer.from([0, 15, 118, 110, 255]))), pngChunk("IEND", Buffer.alloc(0))]);
}

const logo = testLogo();

async function main(): Promise<void> {
  await initStore();
  await mkdir(localBase, { recursive: true });
  const engine = new DaytonaEngine();
  await engine.writeBinaryFile(syntheticUserId, `${remoteBase}/brand-logo.png`, logo);

  const brand = {
    companyName: "Chusky Artifact QA",
    tagline: "Verified Daytona deliverables",
    logoPath: `${remoteBase}/brand-logo.png`,
    preset: "brand" as const,
    primary: "123B5D",
    accent: "0F766E",
    secondary: "2563EB",
    background: "F8FAFC",
    surface: "ECFEFF",
    text: "142337",
    muted: "496580",
    footer: "Live Daytona quality check",
  };
  const sections = [{
    heading: "Verification summary",
    body: "This artifact was generated by Chusky's guarded Daytona pipeline. It exercises branded typography, a valid logo, readable content, and structural validation.",
    bullets: ["Built by the native artifact generator", "Validated before registration", "Retained for visual inspection"],
    table: { headers: ["Check", "Result"], rows: [["Branding", "Applied"], ["Validation", "Passed"], ["Delivery bytes", "Downloaded"]] },
    columnWidths: [3, 2],
    imagePath: `${remoteBase}/brand-logo.png`,
    imageAltText: "Chusky artifact QA test logo",
    imageWidth: 0.6,
  }];

  const [pdf, docx, presentation, spreadsheet] = await Promise.all([
    engine.createPdf(syntheticUserId, { title: "Live branded PDF", sections, brand, path: `${remoteBase}/live-branded.pdf` }),
    engine.createDocument(syntheticUserId, { title: "Live branded Word document", sections, brand, path: `${remoteBase}/live-branded.docx` }),
    engine.createPresentation(syntheticUserId, {
      title: "Live branded presentation", brand, path: `${remoteBase}/live-branded.pptx`,
      slides: [
        { title: "Artifact validation", eyebrow: "DAYTONA QA", bullets: ["Brand color system", "Logo on every slide", "Office package validation"], imagePaths: [`${remoteBase}/brand-logo.png`], imageAltTexts: ["Chusky artifact QA test logo"], layout: "hero" },
        { title: "Measured checks", chart: { categories: ["PDF", "DOCX", "PPTX", "XLSX"], series: [{ name: "Validation", values: [100, 100, 100, 100] }] }, layout: "chart" },
      ],
    }),
    engine.createSpreadsheet(syntheticUserId, {
      title: "Live branded workbook", brand, path: `${remoteBase}/live-branded.xlsx`,
      sheets: [{ name: "Verification", rows: { headers: ["Format", "Brand", "QA state"], rows: [["PDF", "Applied", "Passed"], ["DOCX", "Applied", "Passed"], ["PPTX", "Applied", "Passed"], ["XLSX", "Applied", "Passed"]] } }],
    }),
  ]);

  const artifacts = [pdf, docx, presentation, spreadsheet];
  const report: Array<Record<string, unknown>> = [];
  for (const artifact of artifacts) {
    const downloaded = await engine.downloadArtifact(syntheticUserId, artifact.id);
    if (!downloaded.data.length) throw new Error(`Downloaded ${artifact.name} is empty`);
    await writeFile(join(localBase, downloaded.name), downloaded.data);
    report.push({ name: downloaded.name, type: downloaded.type, bytes: downloaded.size, remotePath: artifact.path });
  }
  await writeFile(join(localBase, "report.json"), `${JSON.stringify({ runId, syntheticUserId, remoteBase, artifacts: report }, null, 2)}\n`);
  process.stdout.write(`${JSON.stringify({ runId, localBase, remoteBase, artifacts: report }, null, 2)}\n`);
}

main().then(() => process.exit(0)).catch((error) => {
  process.stderr.write(`${error instanceof Error ? error.stack ?? error.message : String(error)}\n`);
  process.exit(1);
});
