const baseChuckTools = [
  { type: "function", function: { name: "CHUCK_SEARCH_SKILLS", description: "Search the trusted project skill catalogue for a relevant workflow. This is read-only and searches .chusky/skills metadata and bounded instruction excerpts; it never reads arbitrary filesystem paths or grants tools.", parameters: { type: "object", properties: { query: { type: "string", description: "Task or capability to match, such as create a professional Excel workbook" }, limit: { type: "number", minimum: 1, maximum: 20 } }, required: ["query"] } } },
  { type: "function", function: { name: "CHUCK_LIST_SKILL_FILES", description: "List the files bundled inside one trusted project skill, including nested references, scripts, and assets. Paths are returned relative to that skill and cannot escape its directory.", parameters: { type: "object", properties: { name: { type: "string", description: "Skill name" }, maxFiles: { type: "number", minimum: 1, maximum: 200 } }, required: ["name"] } } },
  { type: "function", function: { name: "CHUCK_READ_SKILL_FILE", description: "Read one text file from a named trusted project skill when its SKILL.md references supporting material. Use a relative path such as SKILL.md or references/formatting.md. Binary assets return metadata only; this tool never executes scripts or reads outside the skill directory.", parameters: { type: "object", properties: { name: { type: "string", description: "Skill name" }, path: { type: "string", description: "Relative path inside the skill; defaults to SKILL.md" }, maxChars: { type: "number", minimum: 1, maximum: 262144 } }, required: ["name"] } } },
  { type: "function", function: { name: "CHUCK_CREATE_PDF", description: "Create and deliver a polished PDF in Daytona with structured text, bullets, tables, images, charts, page breaks, a letterhead, color presets, safe font themes, headers, footers, and page numbers. Use workspace-relative image paths. The generator uses ReportLab with wrapping, proportional image sizing, split/repeating-header tables, alternating row styling, numeric-cell alignment, and a real PDF reopen check; the resulting PDF is structurally validated and rendered page-by-page before delivery. Use the shared brand object whenever company identity matters; its logo appears at the top right of every page. Use this instead of asking the model to hand-write raw PDF bytes.", parameters: { type: "object", properties: { title: { type: "string" }, sections: { type: "array", items: { type: "object" }, description: "Sections may contain heading, body, bullets, table as a matrix or {headers,rows}, optional columnWidths as relative weights such as [1,3,1], imagePath, imageAltText, imageWidth, chart {categories,series}, and pageBreakBefore." }, brand: { type: "object", description: "Reusable company identity for every artifact: companyName, tagline, workspace-relative logoPath, header/footer, preset executive|modern|bold|minimal|brand, fontFamily sans|serif|mono, and six-digit hex colors primary/accent/secondary/background/surface/text/muted. Explicit style values override brand values." }, style: { type: "object", description: "Optional pageSize A4|LETTER|LEGAL, margin in inches, fontSize, preset executive|modern|bold|minimal|brand, fontFamily sans|serif|mono, header, footer, includePageNumbers, author, workspace-relative logoPath, and six-digit hex primary/accent/text/muted overrides. Font themes use ReportLab built-ins for reliable Daytona rendering; do not supply arbitrary font file names." }, path: { type: "string", description: "Optional workspace-relative .pdf output path" }, name: { type: "string", description: "Optional delivered filename" } }, required: ["title", "sections"] } } },
  { type: "function", function: { name: "CHUCK_START_PHONE_CALL", description: "Start an outbound telephone call through the configured provider (Twilio or Bland). Use only after the user gives an E.164 destination and a clear purpose. This places a real call and always requires approval.", parameters: { type: "object", properties: { phoneNumber: { type: "string", description: "Destination in E.164 format, for example +14155550123" }, purpose: { type: "string", description: "Why Chusky is placing this call" } }, required: ["phoneNumber", "purpose"] } } },
  { type: "function", function: { name: "CHUCK_LIST_PHONE_CALLS", description: "List your recent Chusky telephone-call attempts. Credentials and audio are never returned.", parameters: { type: "object", properties: {} } } },
  { type: "function", function: { name: "CHUCK_MEETING_CONTEXT_PREPARE", description: "Prepare a private, reviewable client brief before joining a meeting. Search only the owner's normal-sensitivity saved relationship/business memories for the named client; it never joins a meeting, sends anything, or exposes the brief to attendees. Use this when the owner asks Chusky to represent them to a named client, then ask only the missing high-value questions and obtain confirmation before CHUCK_MEETING_JOIN.", parameters: { type: "object", properties: { clientName: { type: "string", maxLength: 120 }, objective: { type: "string", maxLength: 1500 }, clientContext: { type: "string", maxLength: 4000, description: "Optional owner-supplied facts or meeting goal; do not include credentials or unrelated private information." } }, required: ["clientName"] } } },
  { type: "function", function: { name: "CHUCK_MEETING_JOIN", description: "Join a Zoom, Google Meet, Microsoft Teams, or Webex call as Chusky. By default, join conversationally: follow the discussion, answer naturally, and contribute when useful without waiting for a wake word. Ordinary conversation may create owner-scoped Chusky reminders and follow-up tasks, but cannot read the owner's private memories or task list. For an enabled representative, after the owner confirms a prepared client brief, include clientName plus optional objective/clientContext and set clientContextConfirmed=true to bind a private, scoped meeting mission. Only its normal-sensitivity relationship facts are available in the meeting. If meeting scheduling is enabled in the representative profile, Chusky can use an allowed calendar action and this tool to schedule a follow-up bot. Use addressed mode only when the owner explicitly requests wake-word-only behavior. Do not claim to be the human owner. The meeting ends automatically with the platform; Chusky can also leave when its role is complete or the owner asks. Live audio is processed for interaction; Recall recording and transcript retention are disabled. Recall supports Zoom, Google Meet, Microsoft Teams, and Webex.", parameters: { type: "object", properties: { meetingUrl: { type: "string", description: "HTTPS meeting link from Zoom, Google Meet, Microsoft Teams, or Webex" }, title: { type: "string", description: "Optional private label for this meeting" }, joinAt: { type: "string", description: "Optional future ISO-8601 time, at least 10 minutes and no more than 30 days ahead" }, interactionMode: { type: "string", enum: ["addressed", "copilot", "representative"], description: "Optional override. Use addressed only if the owner explicitly wants wake-word-only behavior. Omit to automatically select the configured company representative or natural conversational participation." }, clientName: { type: "string", maxLength: 120, description: "Named client or relationship context; requires representative mode and prior owner confirmation." }, objective: { type: "string", maxLength: 1500, description: "Specific owner-approved objective for this client meeting." }, clientContext: { type: "string", maxLength: 4000, description: "Optional owner-approved client facts to add to the private meeting brief." }, clientContextConfirmed: { type: "boolean", description: "Set true only after the owner has reviewed and confirmed the prepared client brief. Required whenever clientName, objective, or clientContext is provided." } }, required: ["meetingUrl"] } } },
  { type: "function", function: { name: "CHUCK_MEETING_CONTEXT_LOOKUP", description: "Look up a specific fact from the current meeting's owner-confirmed client brief. Available only inside a representative meeting with a bound client mission. It searches only the normal-sensitivity memory records frozen into that mission; it cannot search the owner's general memory, inbox, files, tasks, or another client.", parameters: { type: "object", properties: { query: { type: "string", maxLength: 500 } }, required: ["query"] } } },
  { type: "function", function: { name: "CHUCK_MEETING_LIST", description: "List your recent Zoom, Google Meet, Microsoft Teams, and Webex assistants and their safe status. Meeting links, transcripts, and provider credentials are never returned.", parameters: { type: "object", properties: { limit: { type: "number", minimum: 1, maximum: 20 } } } } },
  { type: "function", function: { name: "CHUCK_MEETING_STATUS", description: "Check the status of one of your meeting assistants. Meeting ownership is enforced and no meeting URL or transcript is returned.", parameters: { type: "object", properties: { id: { type: "string" } }, required: ["id"] } } },
  { type: "function", function: { name: "CHUCK_MEETING_LEAVE", description: "Leave or cancel one of your meeting assistants. Scheduled bots are cancelled before dispatch; joining or in-call bots are asked to leave immediately.", parameters: { type: "object", properties: { id: { type: "string" } }, required: ["id"] } } },
  { type: "function", function: { name: "CHUCK_MEETING_PROFILE_GET", description: "Read your private meeting representative setup: role, objective, approved company facts, authority boundaries, and exact tools Chusky may use in meetings. This does not return credentials or personal memory.", parameters: { type: "object", properties: {} } } },
    { type: "function", function: { name: "CHUCK_MEETING_PROFILE_UPDATE", description: "Configure the AI representative Chusky uses in meetings. Set its role, objective, communication style, approved company knowledge, authority boundaries, and exact connected-app/native tools it may use. Only direct, non-destructive, non-financial Composio action slugs can be granted; arbitrary Composio execution/discovery and high-impact actions are rejected. Set allowMeetingScheduling=true only when this representative may use an already-approved calendar action to book a follow-up and schedule another Chusky meeting. To activate, provide an objective and enabled=true. Use this only when the account owner asks to configure or update the representative.", parameters: { type: "object", properties: { enabled: { type: "boolean" }, representativeName: { type: "string", maxLength: 80 }, organizationName: { type: "string", maxLength: 120 }, role: { type: "string", enum: ["sales", "client_onboarding", "employee_onboarding", "customer_success", "custom"] }, objective: { type: "string", maxLength: 1500 }, communicationStyle: { type: "string", maxLength: 1500 }, approvedKnowledge: { type: "string", maxLength: 8000, description: "Owner-approved company facts, product details, qualification rules, onboarding steps, and FAQs. Do not include secrets or unrelated personal data." }, authorityBoundaries: { type: "string", maxLength: 2000, description: "Specific offers, commitments, escalation rules, and decisions the agent may or may not make." }, allowedComposioTools: { type: "array", maxItems: 40, items: { type: "string" }, description: "Exact verified direct connected-app action slugs only, such as a CRM create/update action, calendar booking, or standard follow-up email. No COMPOSIO_* meta-tools." }, composioAccountAliases: { type: "object", maxProperties: 40, additionalProperties: { type: "string", maxLength: 160 }, description: "Optional owner-selected Composio account alias/ID by exact action prefix/toolkit (for example GMAIL: work). In meetings, a participant cannot select or override the connected account." }, allowedNativeTools: { type: "array", maxItems: 4, items: { type: "string", enum: ["CHUCK_SET_REMINDER", "CHUCK_LIST_REMINDERS", "CHUCK_TASK_CREATE", "CHUCK_TASK_SCHEDULE"] } }, allowMeetingScheduling: { type: "boolean", description: "Allow a bound representative meeting to schedule a new Recall bot only after an owner-approved calendar action returns a supported meeting link." } }, required: [] } } },
  { type: "function", function: { name: "CHUCK_GENERATE_IMAGE", description: "Generate or edit one or more images with Chusky's native image studio. Use mode=edit with current or saved reference images to modify an image; use mode=generate for new images. References may be current:0, generated:0, or a saved image asset ID/name. Every generated image is automatically persisted as a durable private R2 image asset and the tool result includes its asset ID and fresh download URL, so later actions such as Instagram uploads can reuse the exact image. Supports count 1-10 and provider-specific studio controls. The default x-ai/grok-imagine-image-2.0 supports 1K/2K resolution, the documented aspect ratios, low/medium quality, one output per request, and up to three input references; unsupported generic controls are filtered automatically. For a standalone image request, leave destination unset (or use telegram) so the result is delivered to the active channel. Use destination=daytona or both only when the image is needed as a workspace/artifact input or the user explicitly asks to save it there; workspacePath must be workspace-relative.", parameters: { type: "object", properties: { prompt: { type: "string", description: "Complete visual brief or edit instruction" }, mode: { type: "string", enum: ["generate", "edit", "reference_variations"], description: "Generation mode; edit requires at least one reference" }, references: { type: "array", items: { type: "string" }, description: "Reference selectors: current:0, generated:0, or a saved image asset ID/name" }, count: { type: "integer", minimum: 1, maximum: 10, description: "Number of images to generate; defaults to 1" }, aspectRatio: { type: "string", description: "Provider-specific aspect ratio; Grok supports 1:1, 3:4, 4:3, 9:16, 16:9, 2:3, 3:2, 9:19.5, 19.5:9, 9:20, 20:9, 1:2, 2:1, or auto" }, resolution: { type: "string", enum: ["512", "1K", "2K", "4K"] }, size: { type: "string", description: "Provider-specific pixel size; unsupported values are omitted by the active model" }, quality: { type: "string", enum: ["auto", "low", "medium", "high"], description: "Grok supports low or medium; high is safely mapped to medium" }, outputFormat: { type: "string", enum: ["png", "jpeg", "webp"] }, background: { type: "string", enum: ["auto", "transparent", "opaque"] }, seed: { type: "integer" }, destination: { type: "string", enum: ["telegram", "daytona", "both"], default: "telegram", description: "Standalone images default to the active channel/Telegram. Use daytona or both only for workspace/artifact work or an explicit save request." }, workspacePath: { type: "string", description: "Workspace-relative output path when destination includes daytona; multiple images receive -1, -2 suffixes" } }, required: ["prompt"] } } },
  { type: "function", function: { name: "CHUCK_CREATE_TRIGGER", description: "Create a Composio trigger for the user.", parameters: { type: "object", properties: { slug: { type: "string" }, triggerConfig: { type: "object", additionalProperties: true } }, required: ["slug"] } } },
  { type: "function", function: { name: "CHUCK_GENERATE_VIDEO", description: "Start native asynchronous video generation. Use references for saved/current/generated images; use frameMode=first_frame or last_frame when the reference must be an exact frame, otherwise use reference guidance. Supports duration, aspect ratio, resolution, exact size, generated audio, and reference images when the selected video model supports them. By default send the completed video to Telegram. Daytona paths must be workspace-relative.", parameters: { type: "object", properties: { prompt: { type: "string", description: "Complete video brief" }, references: { type: "array", items: { type: "string" }, description: "Reference selectors: current:0, generated:0, or saved image asset ID/name" }, frameMode: { type: "string", enum: ["reference", "first_frame", "last_frame"] }, duration: { type: "integer", minimum: 1, maximum: 30 }, aspectRatio: { type: "string" }, resolution: { type: "string", enum: ["480p", "720p", "1080p", "2K"] }, size: { type: "string", description: "Exact pixel size such as 1280x720" }, generateAudio: { type: "boolean" }, destination: { type: "string", enum: ["telegram", "daytona", "both"], description: "Where the completed result goes; defaults to telegram" }, workspacePath: { type: "string", description: "Workspace-relative output path used only when destination is daytona or both" } }, required: ["prompt"] } } },
  { type: "function", function: { name: "CHUCK_CREATE_PRESENTATION", description: "Create and deliver a polished, valid PowerPoint through Chusky's built-in OOXML generator. It does not download Python packages inside Daytona. Use this for new PPTX decks instead of hand-writing XML. It adds a designed cover, reusable masters, consistent typography, accessible image alt text, slide numbers, styled tables, readable charts, layout-aware spacing, and a supplied brand logo on every slide. Supports a cover plus 1-30 structured slides. Each slide requires title and can include body, bullets, imagePaths, imageAltTexts, imageFit (contain or cover), backgroundImagePath, backgroundImageAltText, overlayColor, overlayOpacity (0-100), textColor, table, chart, metrics, quote, eyebrow, notes, and layout. Layouts: auto, title, section, two_column, hero, metrics, comparison, timeline, image_focus, background, chart, table, quote, closing. Use backgroundImagePath for a full-bleed image; the generator preserves its aspect ratio with cover fitting, adds a configurable readability scrim and left text safe zone, and chooses a high-contrast foreground color unless textColor is supplied. Do not provide backgroundImagePath and imagePaths on the same slide. A table can be a cell matrix or { headers: string[], rows: string[][] }; empty optional tables are ignored. Each slide supports either a table or a chart, not both. Use the shared brand object for companyName, tagline, logoPath, style preset, and palette. Explicit style values override brand values. The deck is structurally validated, render-checked, then delivered as an artifact.", parameters: { type: "object", properties: { title: { type: "string" }, slides: { type: "array", items: { type: "object" }, description: "Each slide requires title. Optional fields: body, bullets, imagePaths, imageAltTexts, imageFit, backgroundImagePath, backgroundImageAltText, overlayColor, overlayOpacity, textColor, table, chart, metrics [{label,value,detail}], quote, eyebrow, notes, accent, and layout." }, brand: { type: "object", description: "Reusable company identity: companyName, tagline, workspace-relative logoPath, header/footer, preset executive|modern|bold|minimal|brand, fontFamily sans|serif|mono, and six-digit hex colors." }, style: { type: "object", description: "Optional design system: preset executive|modern|bold|minimal|brand; six-digit hex color overrides; fontFace; headingFontFace; footer; includeSlideNumbers; workspace-relative logoPath." }, path: { type: "string", description: "Optional workspace-relative .pptx output path" }, name: { type: "string", description: "Optional delivered filename" } }, required: ["title", "slides"] } } },
  { type: "function", function: { name: "CHUCK_CREATE_DOCUMENT", description: "Create and deliver a genuine, styled DOCX in Daytona. Use instead of a hand-written DOCX script when the user needs a professional Word document. It supports headings, rich body text, bullets, banded tables, images, captions, page breaks, a letterhead header, top-right company logo, footer, and shared brand palettes. The DOCX is structurally validated and render-checked before delivery.", parameters: { type: "object", properties: { title: { type: "string" }, sections: { type: "array", items: { type: "object" }, description: "Same structured sections as CHUCK_CREATE_PDF: heading, body, bullets, table or {headers,rows}, imagePath, imageAltText, imageWidth, and pageBreakBefore." }, brand: { type: "object", description: "Reusable company identity: companyName, tagline, workspace-relative logoPath, header/footer, preset executive|modern|bold|minimal|brand, fontFamily sans|serif|mono, and six-digit hex colors." }, style: { type: "object", description: "Optional explicit style overrides. Use workspace-relative logoPath. Explicit style values override brand values." }, path: { type: "string", description: "Optional workspace-relative .docx output path" }, name: { type: "string" } }, required: ["title", "sections"] } } },
  { type: "function", function: { name: "CHUCK_CREATE_SPREADSHEET", description: "Create and deliver a genuine branded XLSX workbook in Daytona. Use this for polished data workbooks rather than registering an unverified script output. Each sheet receives a company header, optional top-right PNG/JPEG logo, tab color, frozen headers, fitted columns, styled banded tables, and the shared brand palette. For an advanced native Excel chart not expressible here, create the verified data workbook first and then use Daytona to add it; never claim a chart exists unless it is in the returned workbook.", parameters: { type: "object", properties: { title: { type: "string" }, sheets: { type: "array", items: { type: "object" }, description: "1-12 sheets. Each needs name and rows as a cell matrix or {headers,rows}; optional tabColor is a six-digit hex color." }, brand: { type: "object", description: "Reusable company identity: companyName, tagline, workspace-relative PNG/JPEG logoPath, preset executive|modern|bold|minimal|brand, fontFamily, and six-digit hex colors." }, style: { type: "object", description: "Optional explicit palette/style overrides. Explicit style values override brand values." }, path: { type: "string", description: "Optional workspace-relative .xlsx output path" }, name: { type: "string" } }, required: ["title", "sheets"] } } },
  { type: "function", function: { name: "CHUCK_VIDEO_STATUS", description: "Check the status of your recent asynchronous video-generation jobs. Use an optional job ID for one exact job; this is read-only and never starts or cancels generation.", parameters: { type: "object", properties: { id: { type: "string", description: "Optional video job ID" }, limit: { type: "number", minimum: 1, maximum: 10, description: "Maximum recent jobs to return; defaults to 5" } } } } },
  { type: "function", function: { name: "CHUCK_SET_REMINDER", description: "Set a durable one-time reminder. Provide delaySeconds or a future ISO runAt.", parameters: { type: "object", properties: { text: { type: "string" }, delaySeconds: { type: "number" }, runAt: { type: "string", description: "Future ISO-8601 timestamp" } }, required: ["text"] } } },
  { type: "function", function: { name: "CHUCK_LIST_REMINDERS", description: "List the user's active reminders.", parameters: { type: "object", properties: {} } } },
  { type: "function", function: { name: "CHUCK_CANCEL_REMINDER", description: "Cancel one of the user's reminders by ID.", parameters: { type: "object", properties: { id: { type: "string" } }, required: ["id"] } } },
  { type: "function", function: { name: "CHUCK_SCHEDULE_JOB", description: "Schedule a recurring job using a 5-field CRON expression. When Maya, Elena, or another specialist calls this, the schedule is permanently bound to that specialist's current typed contract and each occurrence invokes that specialist directly. Legacy Chusky-created schedules continue through Chusky. Use text as the concrete recurring objective.", parameters: { type: "object", properties: { text: { type: "string", description: "Concrete objective to execute on every occurrence" }, cron: { type: "string", description: "5-field CRON expression; include CRON_TZ=<IANA timezone> when needed" } }, required: ["text", "cron"] } } },
  { type: "function", function: { name: "CHUCK_LIST_JOBS", description: "List the user's active recurring jobs.", parameters: { type: "object", properties: {} } } },
  { type: "function", function: { name: "CHUCK_CANCEL_JOB", description: "Cancel one of the user's recurring jobs by ID.", parameters: { type: "object", properties: { id: { type: "string" } }, required: ["id"] } } },
  { type: "function", function: { name: "CHUCK_SCRATCHPAD_WRITE", description: "Save a private per-user working note for later turns.", parameters: { type: "object", properties: { key: { type: "string" }, content: { type: "string" } }, required: ["key", "content"] } } },
  { type: "function", function: { name: "CHUCK_SCRATCHPAD_READ", description: "Read private scratchpad notes, optionally filtered by a search query. Meeting outcomes are saved under keys like meeting:<meeting-id>; read those notes when the user asks about a past meeting, its decisions, or follow-up actions.", parameters: { type: "object", properties: { query: { type: "string" } } } } },
  { type: "function", function: { name: "CHUCK_SCRATCHPAD_CLEAR", description: "Clear one private scratchpad note or the entire scratchpad.", parameters: { type: "object", properties: { key: { type: "string" } } } } },
  { type: "function", function: { name: "CHUCK_SAVE_MEMORY", description: "Save an explicit durable memory in the correct category. Use profile/personal/preferences for the user, business for work context, relationship for a person, project for a mission, procedural for an approved playbook, episodic for a meaningful event, document for sourced file knowledge, and negative for a do-not rule. Never save casual conversation or secrets unless explicitly requested.", parameters: { type: "object", properties: { category: { type: "string", enum: ["profile", "personal", "preference", "business", "relationship", "project", "procedural", "episodic", "document", "negative", "fact", "instruction"] }, key: { type: "string" }, value: { type: "string" }, source: { type: "string" }, confidence: { type: "number", minimum: 0, maximum: 1 }, sensitivity: { type: "string", enum: ["normal", "sensitive"] }, projectId: { type: "string" }, personKey: { type: "string" }, reviewAt: { type: "number" }, expiresAt: { type: "number" } }, required: ["category", "key", "value"] } } },
  { type: "function", function: { name: "CHUCK_UPDATE_MEMORY", description: "Update an existing durable memory when the user clearly corrects, changes, or evolves it. Identify the record by id or key; use category to disambiguate a key. Preserve the original memory identity and update only the changed fields. Never update based on an uncertain guess.", parameters: { type: "object", properties: { id: { type: "string" }, key: { type: "string" }, category: { type: "string", enum: ["profile", "personal", "preference", "business", "relationship", "project", "procedural", "episodic", "document", "negative", "fact", "instruction"] }, newCategory: { type: "string", enum: ["profile", "personal", "preference", "business", "relationship", "project", "procedural", "episodic", "document", "negative", "fact", "instruction"] }, newKey: { type: "string" }, value: { type: "string" }, source: { type: "string" }, confidence: { type: "number", minimum: 0, maximum: 1 }, sensitivity: { type: "string", enum: ["normal", "sensitive"] }, projectId: { type: "string" }, personKey: { type: "string" }, reviewAt: { type: "number" }, expiresAt: { type: "number" } }, required: ["value"] } } },
  { type: "function", function: { name: "CHUCK_SAVE_IMAGE_ASSET", description: "Save a current user-provided image or an image generated earlier in this run as a durable private image asset in R2. Use when the user asks to remember, save, or designate an image such as a logo, banner, product reference, or brand asset. Include a stable name, purpose, and factual description.", parameters: { type: "object", properties: { name: { type: "string" }, purpose: { type: "string" }, description: { type: "string" }, tags: { type: "array", items: { type: "string" } }, source: { type: "string", enum: ["current", "generated"], description: "Whether to save the current user image or an image generated earlier in this run; defaults to current" }, sourceIndex: { type: "number", minimum: 0, description: "Zero-based image index; defaults to 0" } }, required: ["name", "purpose"] } } },
  { type: "function", function: { name: "CHUCK_SEARCH_IMAGE_ASSETS", description: "Search the user's saved private image assets by name, purpose, tags, or visual description. Results return metadata and asset IDs, not raw image bytes.", parameters: { type: "object", properties: { query: { type: "string" }, limit: { type: "number", minimum: 1, maximum: 10 } } } } },
  { type: "function", function: { name: "CHUCK_GET_IMAGE_ASSET", description: "Retrieve one saved private image asset by ID or exact name. The returned image is supplied back to the vision-capable model for inspection; do not expose its private URL to the user unless explicitly needed.", parameters: { type: "object", properties: { id: { type: "string" } }, required: ["id"] } } },
  { type: "function", function: { name: "CHUCK_FORGET_IMAGE_ASSET", description: "Permanently remove a saved image asset from private R2 storage and its Vector index when the user explicitly asks.", parameters: { type: "object", properties: { id: { type: "string" } }, required: ["id"] } } },
  { type: "function", function: { name: "CHUCK_SEARCH_MEMORY", description: "Search only the user's relevant saved memories. A query is preferred; never request or return the entire memory store. Filter by category, projectId, or personKey when the context identifies one. Results are bounded and exclude expired records.", parameters: { type: "object", properties: { query: { type: "string" }, category: { type: "string", enum: ["profile", "personal", "preference", "business", "relationship", "project", "procedural", "episodic", "document", "negative", "fact", "instruction"] }, projectId: { type: "string" }, personKey: { type: "string" }, limit: { type: "number", minimum: 1, maximum: 20 } } } } },
  { type: "function", function: { name: "CHUCK_FORGET_MEMORY", description: "Forget a saved memory by key or ID when explicitly requested.", parameters: { type: "object", properties: { key: { type: "string" } }, required: ["key"] } } },
  { type: "function", function: { name: "CHUCK_ATTENTION_STATE", description: "Read or explicitly update Chusky's durable attention state: observations, open loops, attention candidates, standing orders, delivery preferences, relationships, and project states. Do not use for casual conversation; only persist state the user explicitly asks to track or update.", parameters: { type: "object", properties: {
    action: { type: "string", enum: ["create", "list", "update"] }, kind: { type: "string", enum: ["observation", "open_loop", "attention_candidate", "standing_order", "delivery_preference", "relationship", "project_state"] }, id: { type: "string" }, query: { type: "string" }, status: { type: "string" }, limit: { type: "number" },
    source: { type: "string" }, eventType: { type: "string" }, summary: { type: "string" }, title: { type: "string" }, objective: { type: "string" }, dueAt: { type: "number" }, priority: { type: "number" }, confidence: { type: "number" }, importance: { type: "number" }, novelty: { type: "number" }, reason: { type: "string" }, proposedAction: { type: "string" }, candidateType: { type: "string", enum: ["nudge", "digest", "prepare", "ask", "act"] },
    name: { type: "string" }, instruction: { type: "string" }, authority: { type: "string", enum: ["observe", "prepare", "execute_reversible"] }, scope: { type: "array", items: { type: "string" } }, provider: { type: "string" }, conversationId: { type: "string" }, enabled: { type: "boolean" }, mode: { type: "string", enum: ["immediate", "digest", "silent"] },
    personKey: { type: "string" }, projectKey: { type: "string" }, role: { type: "string" }, notes: { type: "string" }, currentPhase: { type: "string" }, nextAction: { type: "string" }, blockers: { type: "array", items: { type: "string" } }, lastInteractionAt: { type: "number" }, lastActivityAt: { type: "number" },
  }, required: ["action", "kind"] } } },
  { type: "function", function: { name: "CHUCK_TASK_CREATE", description: "Create a durable, resumable task for the user. Use before beginning work that may span multiple turns or require a computer workspace.", parameters: { type: "object", properties: { title: { type: "string" }, objective: { type: "string" }, workspaceId: { type: "string" } }, required: ["title", "objective"] } } },
  { type: "function", function: { name: "CHUCK_TASK_LIST", description: "List the user's durable tasks. Optionally filter by one or more lifecycle statuses.", parameters: { type: "object", properties: { statuses: { type: "array", items: { type: "string", enum: ["queued", "running", "blocked", "completed", "failed", "cancelled"] } } } } } },
  { type: "function", function: { name: "CHUCK_TASK_GET", description: "Read a durable task, including its latest checkpoint and next action.", parameters: { type: "object", properties: { id: { type: "string" } }, required: ["id"] } } },
  { type: "function", function: { name: "CHUCK_TASK_CHECKPOINT", description: "Persist concise progress and the exact next action for a running task. Use after meaningful work and before ending a turn.", parameters: { type: "object", properties: { id: { type: "string" }, checkpoint: { type: "string" }, nextAction: { type: "string" } }, required: ["id", "checkpoint"] } } },
  { type: "function", function: { name: "CHUCK_TASK_BLOCK", description: "Record why an unfinished durable task cannot proceed and what is needed next. Use when a dependency, permission, or decision blocks progress.", parameters: { type: "object", properties: { id: { type: "string" }, reason: { type: "string" }, nextAction: { type: "string" } }, required: ["id", "reason"] } } },
  { type: "function", function: { name: "CHUCK_TASK_COMPLETE", description: "Mark a durable task complete only after its objective is achieved, with a concise result.", parameters: { type: "object", properties: { id: { type: "string" }, result: { type: "string" } }, required: ["id", "result"] } } },
  { type: "function", function: { name: "CHUCK_TASK_CANCEL", description: "Cancel one of the user's unfinished durable tasks.", parameters: { type: "object", properties: { id: { type: "string" } }, required: ["id"] } } },
  { type: "function", function: { name: "CHUCK_TASK_RETRY", description: "Requeue a failed, blocked, or cancelled durable task while preserving its checkpoint.", parameters: { type: "object", properties: { id: { type: "string" } }, required: ["id"] } } },
  { type: "function", function: { name: "CHUCK_TASK_SCHEDULE", description: "Schedule an existing durable task for a future time. Use only when the user explicitly asks Chusky to continue it later.", parameters: { type: "object", properties: { id: { type: "string" }, delaySeconds: { type: "number" }, runAt: { type: "string", description: "Future ISO-8601 timestamp" } }, required: ["id"] } } },
  { type: "function", function: { name: "CHUCK_DAYTONA_WORKSPACE", description: "Create or inspect Chusky's private isolated Daytona computer workspace.", parameters: { type: "object", properties: { action: { type: "string", enum: ["get", "create", "status", "pause", "archive"] } }, required: ["action"] } } },
  { type: "function", function: { name: "CHUCK_DAYTONA_EXECUTE", description: "Run a bounded command of up to 64,000 characters in the user's isolated Daytona workspace. Use for short code, analysis, and file operations. Prefer a workspace-relative cwd such as workspace or workspace/project; the common /home/user/... form is normalized automatically. For servers, watchers, installs, or work that may exceed the timeout, use CHUCK_DAYTONA_PTY instead; always inspect exitCode and timedOut.", parameters: { type: "object", properties: { command: { type: "string" }, cwd: { type: "string" }, timeoutSeconds: { type: "number", description: "Maximum runtime in seconds, from 1 to 900; default 60. Use PTY for longer work." }, purpose: { type: "string" } }, required: ["command", "purpose"] } } },
  { type: "function", function: { name: "CHUCK_DAYTONA_LIST_FILES", description: "List files in the user's isolated Daytona workspace.", parameters: { type: "object", properties: { path: { type: "string" }, depth: { type: "number" } } } } },
  { type: "function", function: { name: "CHUCK_DAYTONA_READ_FILE", description: "Read a bounded text file from the user's isolated Daytona workspace. Do not use it for PDFs, DOCX, PPTX, XLSX, images, audio, video, or ZIP files; use CHUCK_ARTIFACT for deliverables or the Daytona computer for visual inspection.", parameters: { type: "object", properties: { path: { type: "string" }, maxChars: { type: "number" } }, required: ["path"] } } },
  { type: "function", function: { name: "CHUCK_DAYTONA_WRITE_FILE", description: "Write text to a file in the user's isolated Daytona workspace, preferably with a workspace-relative path such as workspace/resume.html. Daytona's common /home/user/resume.html form is normalized automatically.", parameters: { type: "object", properties: { path: { type: "string" }, content: { type: "string" } }, required: ["path", "content"] } } },
  { type: "function", function: { name: "CHUCK_DAYTONA_FIND_FILES", description: "Find text matches in files in the user's isolated Daytona workspace.", parameters: { type: "object", properties: { path: { type: "string" }, pattern: { type: "string" } }, required: ["pattern"] } } },
  { type: "function", function: { name: "CHUCK_DAYTONA_SEARCH_FILES", description: "Search for files by name pattern in the user's isolated Daytona workspace.", parameters: { type: "object", properties: { path: { type: "string" }, pattern: { type: "string" } }, required: ["pattern"] } } },
  { type: "function", function: { name: "CHUCK_DAYTONA_FILE_DETAILS", description: "Get metadata for a file or directory in the user's isolated Daytona workspace.", parameters: { type: "object", properties: { path: { type: "string" } }, required: ["path"] } } },
  { type: "function", function: { name: "CHUCK_DAYTONA_CREATE_FOLDER", description: "Create a folder in the user's isolated Daytona workspace.", parameters: { type: "object", properties: { path: { type: "string" } }, required: ["path"] } } },
  { type: "function", function: { name: "CHUCK_DAYTONA_MOVE_FILES", description: "Move or rename a file or folder in the user's isolated Daytona workspace.", parameters: { type: "object", properties: { source: { type: "string" }, destination: { type: "string" } }, required: ["source", "destination"] } } },
  { type: "function", function: { name: "CHUCK_DAYTONA_DELETE_FILE", description: "Delete a file or folder from the user's isolated Daytona workspace. Requires confirmation.", parameters: { type: "object", properties: { path: { type: "string" }, recursive: { type: "boolean" } }, required: ["path"] } } },
  { type: "function", function: { name: "CHUCK_DAYTONA_DELETE_WORKSPACE", description: "Permanently delete the user's Daytona workspace and all of its retained state. Requires confirmation.", parameters: { type: "object", properties: {} } } },
  { type: "function", function: { name: "CHUCK_DAYTONA_PREVIEW", description: "Get a signed, temporary HTTPS preview URL for a web service running on a Daytona workspace port. Include the returned URL and expiry in the final user-facing response.", parameters: { type: "object", properties: { port: { type: "number" } }, required: ["port"] } } },
  { type: "function", function: { name: "CHUCK_DAYTONA_APP", description: "Operate a durable app project in the isolated Daytona workspace. scaffold creates a Vite React TypeScript or Next.js project in workspace/apps/<id>, initializes an isolated local feature branch, and records it. verify runs typecheck, lint, tests when configured, and a required production build; start always re-runs that verification before launching a durable server and returning a signed preview URL. logs reads only the app's server PTY. visual opens the signed preview and captures a screenshot for model review; review records the model's honest visual assessment. release is only a readiness handoff after executable and visual checks pass—it never deploys or pushes. GitHub push and permanent deployment use their separate approval-gated flows.", parameters: { type: "object", properties: { action: { type: "string", enum: ["scaffold", "verify", "start", "status", "logs", "visual", "review", "branch", "release", "stop", "list"] }, id: { type: "string", description: "Lowercase app identifier, such as client-portal" }, framework: { type: "string", enum: ["vite-react", "nextjs"] }, port: { type: "number" }, expiresInSeconds: { type: "number", description: "Signed preview lifetime, 60-86400 seconds; default 3600" }, branch: { type: "string", description: "Safe local feature branch name; no remote push occurs" }, passed: { type: "boolean", description: "For review only: whether the model actually found the captured visual acceptable" }, summary: { type: "string", description: "For review or release: concise evidence or requested external target" }, target: { type: "string", description: "For release: intended approved deployment target, for example Vercel preview" } }, required: ["action"] } } },
  { type: "function", function: { name: "CHUCK_DAYTONA_CREATE_SNAPSHOT", description: "Create a reusable Daytona snapshot of the user's workspace. Requires confirmation.", parameters: { type: "object", properties: { name: { type: "string" } }, required: ["name"] } } },
  { type: "function", function: { name: "CHUCK_DAYTONA_COMPUTER", description: "Operate the user's persistent Daytona desktop and browser. Use accessibility inspection before coordinate actions. Supports lifecycle, display geometry, screenshots including regions, diagnostics, screen recordings, mouse, keyboard, and accessibility actions. Process diagnostics are only for Daytona desktop infrastructure: novnc (browser handoff), x11vnc, xfce4, or xvfb—never guess browser or chrome. process_status defaults to novnc when no process is supplied.", parameters: { type: "object", properties: { action: { type: "string", enum: ["start", "stop", "status", "display", "display_info", "windows", "process_status", "process_restart", "process_logs", "process_errors", "screenshot", "screenshot_region", "recording_start", "recording_stop", "recording_list", "recording_get", "recording_delete", "recording_download", "mouse_position", "mouse_move", "mouse_click", "mouse_drag", "mouse_scroll", "keyboard_type", "keyboard_press", "keyboard_hotkey", "accessibility_tree", "accessibility_find", "accessibility_focus", "accessibility_invoke", "accessibility_set_value"] }, x: { type: "number" }, y: { type: "number" }, width: { type: "number" }, height: { type: "number" }, startX: { type: "number" }, startY: { type: "number" }, endX: { type: "number" }, endY: { type: "number" }, button: { type: "string", enum: ["left", "right", "middle"] }, double: { type: "boolean" }, direction: { type: "string", enum: ["up", "down"] }, amount: { type: "number" }, text: { type: "string" }, delayMs: { type: "number" }, key: { type: "string" }, modifiers: { type: "array", items: { type: "string" } }, keys: { type: "string" }, showCursor: { type: "boolean" }, scope: { type: "string", enum: ["focused", "pid", "all"] }, maxDepth: { type: "number" }, role: { type: "string" }, name: { type: "string" }, nameMatch: { type: "string", enum: ["exact", "substring", "regex"] }, limit: { type: "number" }, nodeId: { type: "string" }, nodeAction: { type: "string" }, value: { type: "string" }, processName: { type: "string", enum: ["novnc", "x11vnc", "xfce4", "xvfb", "browser", "chrome", "desktop", "vnc"] }, recordingId: { type: "string" }, label: { type: "string" }, path: { type: "string" } }, required: ["action"] } } },
  { type: "function", function: { name: "CHUCK_DAYTONA_PAUSE", description: "Pause the user's Daytona workspace while preserving its filesystem state.", parameters: { type: "object", properties: {} } } },
  { type: "function", function: { name: "CHUCK_DAYTONA_PTY", description: "Create and control a durable interactive terminal process in the user's Daytona workspace. Use create once, then write/read/status/resize/kill with the returned session ID.", parameters: { type: "object", properties: { action: { type: "string", enum: ["create", "write", "read", "status", "resize", "kill"] }, id: { type: "string" }, input: { type: "string" }, cwd: { type: "string" }, cols: { type: "number" }, rows: { type: "number" } }, required: ["action"] } } },
  { type: "function", function: { name: "CHUCK_DAYTONA_GIT", description: "Use Daytona's Git API for a repository in the isolated workspace. Clone, inspect, branch, pull, stage, commit, and push. Push is externally visible and requires approval.", parameters: { type: "object", properties: { action: { type: "string", enum: ["clone", "status", "branches", "create_branch", "checkout", "pull", "add", "commit", "push"] }, path: { type: "string" }, repoUrl: { type: "string" }, branch: { type: "string" }, files: { type: "array", items: { type: "string" } }, message: { type: "string" }, author: { type: "string" }, email: { type: "string" }, remote: { type: "string" } }, required: ["action"] } } },
  { type: "function", function: { name: "CHUCK_DAYTONA_BROWSER", description: "Browse the web in the user's Daytona desktop through the official Computer Use API. Open http(s) URLs, inspect accessibility snapshots, find elements by role/name, invoke or fill accessible controls, inspect windows, take screenshots, manage VNC/recordings when needed, and use keyboard navigation. Verify the page after each interaction. Browser state is retained in the user's Daytona workspace. During an authenticated vault session, use find before invoke/fill; coordinate clicks and keyboard submit are disabled, and checkout/account changes require the matching vaultAction so Chusky can enforce identity policy.", parameters: { type: "object", properties: { action: { type: "string", enum: ["start", "stop", "status", "open", "snapshot", "find", "focus", "invoke", "fill", "windows", "display_info", "screenshot", "screenshot_region", "recording_start", "recording_stop", "recording_list", "recording_get", "recording_delete", "recording_download", "click", "type", "press", "scroll", "back", "forward", "refresh"] }, url: { type: "string" }, x: { type: "number" }, y: { type: "number" }, width: { type: "number" }, height: { type: "number" }, text: { type: "string" }, value: { type: "string" }, key: { type: "string" }, keys: { type: "string" }, direction: { type: "string", enum: ["up", "down"] }, amount: { type: "number" }, maxDepth: { type: "number" }, role: { type: "string" }, name: { type: "string" }, nameMatch: { type: "string", enum: ["exact", "substring", "regex"] }, limit: { type: "number" }, nodeId: { type: "string" }, nodeAction: { type: "string" }, processName: { type: "string" }, recordingId: { type: "string" }, label: { type: "string" }, path: { type: "string" }, vaultAction: { type: "string", enum: ["browse", "search", "add_to_cart", "add_to_wishlist", "checkout", "place_order", "purchase", "change_address", "add_payment_method"] } }, required: ["action"] } } },
  { type: "function", function: { name: "CHUCK_VAULT_SAVE", description: "Use this when the user asks to connect, link, add, save, sign in to, or log in to an ordinary website account that is not being connected through an explicitly supported Composio app. Start a private one-time setup for that website login. This tool never accepts a username, password, cookie, code, or secret. It returns a private HTTPS form where the user enters credentials directly into Chusky's trusted server; the model cannot read those values.", parameters: { type: "object", properties: { service: { type: "string" }, origin: { type: "string", description: "Exact HTTPS origin, e.g. https://www.amazon.com" }, loginUrl: { type: "string" }, logoutUrl: { type: "string" }, usernameFieldLabel: { type: "string", description: "Exact accessibility label for the login identifier field" }, passwordFieldLabel: { type: "string", description: "Exact accessibility label for the password field" }, submitButtonLabel: { type: "string", description: "Exact accessibility label for the sign-in button" } }, required: ["service", "origin"] } } },
  { type: "function", function: { name: "CHUCK_VAULT_LIST", description: "List only the caller's connected websites and safe session metadata. It never returns usernames, passwords, cookies, encrypted values, or keys.", parameters: { type: "object", properties: {} } } },
  { type: "function", function: { name: "CHUCK_VAULT_STATUS", description: "Check safe retained-Daytona authentication session metadata for one connected website or all of the caller's websites. It never returns credentials or cookies.", parameters: { type: "object", properties: { service: { type: "string" } } } } },
  { type: "function", function: { name: "CHUCK_VAULT_LOGIN", description: "Use a saved website identity through the trusted credential broker. It decrypts and fills credentials only inside Daytona, then returns only authenticated status and safe session metadata. Never attempt to type a password with any browser tool.", parameters: { type: "object", properties: { service: { type: "string" } }, required: ["service"] } } },
  { type: "function", function: { name: "CHUCK_VAULT_LOGOUT", description: "Stop reusing Chusky's saved authenticated browser session for one website. This preserves the encrypted login until the user explicitly replaces or deletes it.", parameters: { type: "object", properties: { service: { type: "string" } }, required: ["service"] } } },
  { type: "function", function: { name: "CHUCK_SHOPPING_START", description: "Start a private, durable shopping plan for physical goods. Use when the user asks to buy, order, restock, find, compare, or add products to a cart. It suggests relevant retailers but never treats Amazon as the only option and never accepts credentials or payment details.", parameters: { type: "object", properties: { items: { type: "array", items: { type: "string" }, description: "1-80 products or shopping-list items" }, category: { type: "string", enum: ["groceries", "household", "meal_kit", "fashion", "electronics", "health_beauty", "home", "other"] }, retailer: { type: "string", description: "Optional retailer the user already chose" }, country: { type: "string", description: "Two-letter delivery country code, such as US or GB" }, city: { type: "string" }, postcode: { type: "string" }, budget: { type: "number", description: "Maximum basket budget, excluding unknown taxes or delivery fees" }, currency: { type: "string", description: "Three-letter currency code, such as USD or GBP" }, deliveryPreference: { type: "string", enum: ["delivery", "pickup", "either"] }, notes: { type: "string", description: "Dietary needs, preferred brands, substitutions, sizes, or other user-provided shopping constraints" } }, required: ["items"] } } },
  { type: "function", function: { name: "CHUCK_SHOPPING_LIST", description: "List the caller's recent private shopping plans, their selected retailer, and their safe workflow status. It never returns website credentials, cookies, payment data, or delivery addresses.", parameters: { type: "object", properties: { limit: { type: "number", minimum: 1, maximum: 50 } } } } },
  { type: "function", function: { name: "CHUCK_SHOPPING_SELECT_RETAILER", description: "Choose the retailer for a private shopping plan. Use a suggested retailer name or, for any other retailer, supply its clean HTTPS origin. Then continue with the vault/browser flow; never ask for credentials in chat.", parameters: { type: "object", properties: { id: { type: "string" }, retailer: { type: "string" }, origin: { type: "string", description: "Required only for a retailer outside Chusky's starter catalogue; clean HTTPS origin, such as https://shop.example.com" } }, required: ["id", "retailer"] } } },
  { type: "function", function: { name: "CHUCK_SHOPPING_UPDATE", description: "Update a private active shopping plan when the user changes their list, budget, location, delivery preference, or shopping constraints. It does not change a website cart by itself.", parameters: { type: "object", properties: { id: { type: "string" }, items: { type: "array", items: { type: "string" } }, category: { type: "string", enum: ["groceries", "household", "meal_kit", "fashion", "electronics", "health_beauty", "home", "other"] }, country: { type: "string" }, city: { type: "string" }, postcode: { type: "string" }, budget: { type: "number" }, currency: { type: "string" }, deliveryPreference: { type: "string", enum: ["delivery", "pickup", "either"] }, notes: { type: "string" } }, required: ["id"] } } },
  { type: "function", function: { name: "CHUCK_SHOPPING_CANCEL", description: "Cancel one private shopping plan. This stops Chusky's plan only; it never removes an external website cart, account, or order.", parameters: { type: "object", properties: { id: { type: "string" } }, required: ["id"] } } },
  { type: "function", function: { name: "CHUCK_ARTIFACT", description: "Create and manage durable user-owned deliverables in Daytona. Create text artifacts, register files generated in the workspace, list/get/delete artifacts, and package workspace files into a ZIP. For DOCX, use a real OOXML generator with explicit page settings, Word styles, readable wrapping, properly sized images with alt text, and non-clipping tables; for XLSX, use a real workbook generator with explicit sheet names, column widths, wrapped cells, frozen headers, formulas, and charts where useful; for PPTX, use the guarded presentation generator or a real OOXML library with layout-aware spacing. Every DOCX, PDF, PPTX, and XLSX registration performs structural validation and page-by-page rendering in Daytona before delivery; the gate fails closed when LibreOffice/Poppler cannot complete the inspection. Use the Daytona computer to inspect rendered pages for clipping, overflow, broken tables, missing images, bad page breaks, and unreadable text before registering. Generate the valid file in Daytona first, then register the exact workspace-relative path returned by the generator; never invent a filename or prepend a workspace prefix. Registration adds the type-appropriate filename extension when missing and can recover one unique basename mismatch.", parameters: { type: "object", properties: { action: { type: "string", enum: ["create", "register", "list", "get", "delete", "package"] }, id: { type: "string" }, name: { type: "string" }, type: { type: "string", enum: ["website", "report", "docx", "presentation", "pdf", "spreadsheet", "image", "video", "zip", "project"] }, path: { type: "string" }, content: { type: "string" }, contentType: { type: "string" }, files: { type: "array", items: { type: "string" } }, removeFile: { type: "boolean" } }, required: ["action"] } } },
  { type: "function", function: { name: "CHUCK_DELEGATE_SUBAGENT", description: "Delegate a task to a specialized domain worker capability under a typed execution contract. Classify the objective first: lucas is mandatory for software and Daytona engineering; nora is for source-backed technical, market, competitor, and web research; leo is for marketing, copy, images, video, and brand assets; maya is for social publishing and integrations; sofia is for phone or voice calls; dexter is for GUI or computer use; elena is for durable tasks, reminders, and schedules. Split mixed objectives into dependency-ordered delegations. If a mixed request reaches this tool, it is safely sequenced into durable role-scoped stages rather than failing. Nora receives scoped Composio research tools: COMPOSIO_SEARCH_WEB, COMPOSIO_SEARCH_FETCH_URL_CONTENT, COMPOSIO_SEARCH_TOOLS, COMPOSIO_GET_TOOL_SCHEMAS, COMPOSIO_EXECUTE_TOOL, COMPOSIO_MULTI_EXECUTE_TOOL, COMPOSIO_REMOTE_WORKBENCH, and COMPOSIO_REMOTE_BASH_TOOL. Workers can request one missing tool and resume only after Chusky scopes it.", parameters: { type: "object", properties: { worker: { type: "string", enum: ["lucas", "maya", "leo", "sofia", "dexter", "elena", "nora"] }, objective: { type: "string", description: "Clear objective description" }, expectedOutput: { type: "string", description: "Expected result or output spec" }, allowedTools: { type: "array", items: { type: "string" }, description: "Optional native CHUCK_* tool names allowed for this contract" }, allowedComposioTools: { type: "array", items: { type: "string" }, description: "Exact verified Composio slugs scoped to this worker and one task." }, duration: { type: "string", enum: ["5m", "30m", "1h", "3h", "6h", "3d", "1w"], description: "Overall durable worker budget; defaults to 30m" }, timeoutSeconds: { type: "number", minimum: 5, maximum: 300 }, maxToolCalls: { type: "number", minimum: 1, maximum: 100, description: "Per-slice tool-call ceiling; the overall duration remains the safety boundary." } }, required: ["worker", "objective"] } } },
  { type: "function", function: { name: "CHUCK_HANDOFF_SUBAGENT", description: "Hand off an active task or sub-objective to another domain worker capability (nora, lucas, maya, leo, sofia, dexter, elena).", parameters: { type: "object", properties: { targetWorker: { type: "string", enum: ["nora", "lucas", "maya", "leo", "sofia", "dexter", "elena"] }, objective: { type: "string", description: "Objective for target worker" }, expectedOutput: { type: "string" }, context: { type: "object" } }, required: ["targetWorker", "objective"] } } },
  { type: "function", function: { name: "CHUCK_PLAN_DELEGATION", description: "Classify an objective across all matching capabilities and return a deterministic dependency plan before any worker is created. Use this for mixed requests such as build an app, create its marketing assets, and publish them; execute each returned step with its assigned worker and pass only the prior step's handoff.", parameters: { type: "object", properties: { objective: { type: "string", description: "Full objective to decompose" }, allowedTools: { type: "array", items: { type: "string" }, description: "Optional native tools that further clarify the capability" } }, required: ["objective"] } } },
  { type: "function", function: { name: "CHUCK_REQUEST_ADDITIONAL_TOOLS", description: "Worker-only escalation: request a missing capability from Chusky. Do not guess a Composio slug or search the catalogue yourself. State the user-facing intent, why the current allowed tools are insufficient, and an optional provider/toolkit. Chusky will decide whether to use COMPOSIO_SEARCH_TOOL, verify the user's connection, and resume this same paused worker with one narrowly scoped action. This tool never grants or executes a capability itself.", parameters: { type: "object", properties: { intent: { type: "string", description: "What action is needed, expressed as an intent rather than a guessed tool slug" }, reason: { type: "string", description: "Why the worker's current tools cannot complete the task" }, preferredToolkit: { type: "string", description: "Optional likely toolkit, such as github or slack; omit when uncertain" } }, required: ["intent", "reason"] } } },
  { type: "function", function: { name: "CHUCK_RESOLVE_SUBAGENT_TOOL_REQUEST", description: "Supervisor-only durable continuation. After COMPOSIO_SEARCH_TOOL has identified and Chusky has verified exact connected action slugs, notify the specific worker workflow waiting for a tool decision. This resumes the same durable worker task; it never grants a broad toolkit or runs the external action itself.", parameters: { type: "object", properties: { handoffId: { type: "string" }, allowedComposioTools: { type: "array", minItems: 1, items: { type: "string" }, description: "Exact verified Composio action slugs, scoped to the waiting worker's role" } }, required: ["handoffId", "allowedComposioTools"] } } },
  { type: "function", function: { name: "CHUCK_REVIEW_SUBAGENT_ACTION", description: "Supervisor-only review of a specialist risky-action proposal. Chusky must inspect the proposal returned by CHUCK_DELEGATE_SUBAGENT, then approve or deny it itself; this never asks the user for approval. Approving resumes the same durable handoff with the exact reviewed arguments.", parameters: { type: "object", properties: { approvalId: { type: "string" }, decision: { type: "string", enum: ["approve", "deny"] } }, required: ["approvalId", "decision"] } } },
  { type: "function", function: { name: "CHUCK_LIST_SUBAGENTS", description: "List recent subagent delegation handoff records. Use to answer 'What is Lucas doing?', 'Which agent failed?', or 'Show all active workers.'", parameters: { type: "object", properties: { limit: { type: "number", minimum: 1, maximum: 50, description: "Max records to return; defaults to 20" } } } } },
  { type: "function", function: { name: "CHUCK_GET_SUBAGENT_STATUS", description: "Get full status, tool call log, and linked task details for a specific subagent delegation by handoff record ID.", parameters: { type: "object", properties: { id: { type: "string", description: "The handoff record ID" } }, required: ["id"] } } },
  { type: "function", function: { name: "CHUCK_CANCEL_SUBAGENT", description: "Cancel a worker delegation and its linked durable task by handoff record ID. Use when the user says 'cancel Dexter's task' or 'stop the browser agent'. Cannot interrupt mid-flight execution.", parameters: { type: "object", properties: { id: { type: "string", description: "The handoff record ID to cancel" }, reason: { type: "string", description: "Reason for cancellation" } }, required: ["id"] } } },
] as const;

/** Kept separate from the legacy catalogue so the human-browser handoff stays reviewable. */
const shoppingAndBrowserTools = [
  { type: "function", function: { name: "CHUCK_DAYTONA_BROWSER_HANDOFF", description: "Create a short-lived private link to the caller's existing Daytona browser desktop when they must personally complete CAPTCHA, 2FA, consent, or another website-only challenge. It preserves the same browser session for Chusky to resume afterward. Never use in a shared group and never include passwords, cookies, codes, or any secret.", parameters: { type: "object", properties: { shoppingPlanId: { type: "string", description: "Optional private shopping plan to mark as paused while the user completes the website step" }, reason: { type: "string", enum: ["captcha", "two_factor", "age_verification", "site_challenge", "login", "user_requested"] } } } } },
  { type: "function", function: { name: "CHUCK_SHOPPING_PAUSE", description: "Pause a private shopping plan when a website requires CAPTCHA, 2FA, age verification, a login step, or another user-only action. It never changes a website cart or account.", parameters: { type: "object", properties: { id: { type: "string" }, reason: { type: "string", enum: ["captcha", "two_factor", "age_verification", "site_challenge", "login", "user_requested"] } }, required: ["id", "reason"] } } },
  { type: "function", function: { name: "CHUCK_SHOPPING_RESUME", description: "Resume one of the caller's paused private shopping plans after they finish a user-only website step in the retained browser. Inspect the page before taking any new action.", parameters: { type: "object", properties: { id: { type: "string" } }, required: ["id"] } } },
  { type: "function", function: { name: "CHUCK_SHOPPING_SAVE_SITE", description: "Save a user-owned shopping-site preference by name and clean HTTPS origin. This saves no password, cookie, payment data, or website session. The site can then be selected by name in later shopping plans.", parameters: { type: "object", properties: { name: { type: "string" }, origin: { type: "string" }, countries: { type: "array", items: { type: "string" } }, categories: { type: "array", items: { type: "string" } }, supportsDelivery: { type: "boolean" }, supportsPickup: { type: "boolean" } }, required: ["name", "origin"] } } },
  { type: "function", function: { name: "CHUCK_SHOPPING_LIST_SITES", description: "List only the caller's saved shopping-site names and safe metadata. It never returns credentials, cookies, payment details, or browser sessions.", parameters: { type: "object", properties: { limit: { type: "number", minimum: 1, maximum: 100 } } } } },
  { type: "function", function: { name: "CHUCK_SHOPPING_REMOVE_SITE", description: "Remove one of the caller's saved shopping-site preferences. It does not delete a separately saved vault login or any external account.", parameters: { type: "object", properties: { id: { type: "string" } }, required: ["id"] } } },
] as const;

export const chuckTools = [...baseChuckTools, ...shoppingAndBrowserTools] as const;

/** Validate local-tool arguments at the execution boundary, not just in the model prompt. */
export function validateNativeToolArguments(name: string, args: Record<string, unknown>): void {
  const tool = chuckTools.find((item) => item.function.name === name);
  if (!tool) throw new Error(`Unknown native tool: ${name}`);
  const schema = tool.function.parameters as { required?: readonly string[]; properties?: Record<string, { type?: string; enum?: readonly string[]; items?: { type?: string } }> };
  // Models occasionally serialize structured arguments as JSON text, or emit
  // one PDF section instead of a one-item array. Normalize only these safe
  // structural forms before enforcing the schema so a recoverable formatting
  // mistake does not abort an otherwise valid document request.
  for (const [key, rule] of Object.entries(schema.properties ?? {})) {
    if (rule.type !== "array") continue;
    const value = args[key];
    if (typeof value === "string") {
      try {
        const parsed = JSON.parse(value);
        if (Array.isArray(parsed)) args[key] = parsed;
      } catch {
        // The normal type error below remains actionable for non-JSON text.
      }
    } else if (name === "CHUCK_CREATE_PDF" && key === "sections" && value && typeof value === "object" && !Array.isArray(value)) {
      args[key] = [value];
    }
  }
  for (const key of schema.required ?? []) {
    if (!(key in args) || args[key] === undefined || args[key] === null || (typeof args[key] === "string" && !args[key].trim())) throw new Error(`${name} requires argument: ${key}`);
  }
  for (const [key, rule] of Object.entries(schema.properties ?? {})) {
    const value = args[key];
    if (value === undefined || value === null || !rule.type) continue;
    const valid = rule.type === "number" ? typeof value === "number" && Number.isFinite(value)
      : rule.type === "string" ? typeof value === "string"
      : rule.type === "boolean" ? typeof value === "boolean"
      : rule.type === "array" ? Array.isArray(value) && (!rule.items?.type || value.every((item) => typeof item === rule.items?.type))
      : rule.type === "object" ? typeof value === "object" && !Array.isArray(value) : true;
    if (!valid) throw new Error(`${name}.${key} must be ${rule.type === "array" ? "an" : "a"} ${rule.type}`);
    if (rule.enum && !rule.enum.includes(value as string)) throw new Error(`${name}.${key} has an unsupported value`);
  }
}






