export const chuckTools = [
  { type: "function", function: { name: "CHUCK_START_FACETIME_CALL", description: "Start an outbound FaceTime audio call from Chusky. Use only after the user gives an E.164 destination and a clear purpose. This places a real call and always requires approval.", parameters: { type: "object", properties: { phoneNumber: { type: "string", description: "Destination in E.164 format, for example +14155550123" }, purpose: { type: "string", description: "Why Chusky is placing this call" } }, required: ["phoneNumber", "purpose"] } } },
  { type: "function", function: { name: "CHUCK_LIST_FACETIME_CALLS", description: "List your recent Chusky FaceTime call attempts. Credentials and audio are never returned.", parameters: { type: "object", properties: {} } } },
  { type: "function", function: { name: "CHUCK_GENERATE_IMAGE", description: "Generate an image and send it to the user.", parameters: { type: "object", properties: { prompt: { type: "string" } }, required: ["prompt"] } } },
  { type: "function", function: { name: "CHUCK_CREATE_TRIGGER", description: "Create a Composio trigger for the user.", parameters: { type: "object", properties: { slug: { type: "string" }, triggerConfig: { type: "object", additionalProperties: true } }, required: ["slug"] } } },
  { type: "function", function: { name: "CHUCK_GENERATE_VIDEO", description: "Start an asynchronous video generation job.", parameters: { type: "object", properties: { prompt: { type: "string" } }, required: ["prompt"] } } },
  { type: "function", function: { name: "CHUCK_SET_REMINDER", description: "Set a durable one-time reminder. Provide delaySeconds or a future ISO runAt.", parameters: { type: "object", properties: { text: { type: "string" }, delaySeconds: { type: "number" }, runAt: { type: "string", description: "Future ISO-8601 timestamp" } }, required: ["text"] } } },
  { type: "function", function: { name: "CHUCK_LIST_REMINDERS", description: "List the user's active reminders.", parameters: { type: "object", properties: {} } } },
  { type: "function", function: { name: "CHUCK_CANCEL_REMINDER", description: "Cancel one of the user's reminders by ID.", parameters: { type: "object", properties: { id: { type: "string" } }, required: ["id"] } } },
  { type: "function", function: { name: "CHUCK_SCHEDULE_JOB", description: "Schedule a recurring user notification using a 5-field CRON expression.", parameters: { type: "object", properties: { text: { type: "string" }, cron: { type: "string" } }, required: ["text", "cron"] } } },
  { type: "function", function: { name: "CHUCK_LIST_JOBS", description: "List the user's active recurring jobs.", parameters: { type: "object", properties: {} } } },
  { type: "function", function: { name: "CHUCK_CANCEL_JOB", description: "Cancel one of the user's recurring jobs by ID.", parameters: { type: "object", properties: { id: { type: "string" } }, required: ["id"] } } },
  { type: "function", function: { name: "CHUCK_SCRATCHPAD_WRITE", description: "Save a private per-user working note for later turns.", parameters: { type: "object", properties: { key: { type: "string" }, content: { type: "string" } }, required: ["key", "content"] } } },
  { type: "function", function: { name: "CHUCK_SCRATCHPAD_READ", description: "Read private scratchpad notes, optionally filtered by a search query.", parameters: { type: "object", properties: { query: { type: "string" } } } } },
  { type: "function", function: { name: "CHUCK_SCRATCHPAD_CLEAR", description: "Clear one private scratchpad note or the entire scratchpad.", parameters: { type: "object", properties: { key: { type: "string" } } } } },
  { type: "function", function: { name: "CHUCK_SAVE_MEMORY", description: "Save an explicit user fact, preference, profile detail, or instruction for future conversations.", parameters: { type: "object", properties: { category: { type: "string", enum: ["preference", "profile", "fact", "instruction"] }, key: { type: "string" }, value: { type: "string" }, confidence: { type: "number" } }, required: ["category", "key", "value"] } } },
  { type: "function", function: { name: "CHUCK_SEARCH_MEMORY", description: "Search the user's saved structured memories.", parameters: { type: "object", properties: { query: { type: "string" } } } } },
  { type: "function", function: { name: "CHUCK_FORGET_MEMORY", description: "Forget a saved memory by key or ID when explicitly requested.", parameters: { type: "object", properties: { key: { type: "string" } }, required: ["key"] } } },
  { type: "function", function: { name: "CHUCK_ATTENTION_STATE", description: "Read or explicitly update Chusky's durable attention state: observations, open loops, attention candidates, standing orders, delivery preferences, relationships, and project states. Do not use for casual conversation; only persist state the user explicitly asks to track or update.", parameters: { type: "object", properties: {
    action: { type: "string", enum: ["create", "list", "update"] }, kind: { type: "string", enum: ["observation", "open_loop", "attention_candidate", "standing_order", "delivery_preference", "relationship", "project_state"] }, id: { type: "string" }, query: { type: "string" }, status: { type: "string" }, limit: { type: "number" },
    source: { type: "string" }, eventType: { type: "string" }, summary: { type: "string" }, title: { type: "string" }, objective: { type: "string" }, dueAt: { type: "number" }, priority: { type: "number" }, confidence: { type: "number" }, importance: { type: "number" }, novelty: { type: "number" }, reason: { type: "string" }, proposedAction: { type: "string" }, candidateType: { type: "string", enum: ["nudge", "digest", "prepare", "ask", "act"] },
    name: { type: "string" }, instruction: { type: "string" }, authority: { type: "string", enum: ["observe", "prepare", "execute_reversible"] }, scope: { type: "array", items: { type: "string" } }, provider: { type: "string" }, conversationId: { type: "string" }, enabled: { type: "boolean" }, mode: { type: "string", enum: ["immediate", "digest", "silent"] },
    personKey: { type: "string" }, projectKey: { type: "string" }, role: { type: "string" }, notes: { type: "string" }, currentPhase: { type: "string" }, nextAction: { type: "string" }, blockers: { type: "array", items: { type: "string" } }, lastInteractionAt: { type: "number" }, lastActivityAt: { type: "number" },
  }, required: ["action", "kind"] } } },
  { type: "function", function: { name: "CHUCK_TASK_CREATE", description: "Create a durable, resumable task for the user. Use before beginning work that may span multiple turns or require a computer workspace.", parameters: { type: "object", properties: { title: { type: "string" }, objective: { type: "string" }, workspaceId: { type: "string" } }, required: ["title", "objective"] } } },
  { type: "function", function: { name: "CHUCK_TASK_LIST", description: "List the user's durable tasks. Optionally filter by one or more lifecycle statuses.", parameters: { type: "object", properties: { statuses: { type: "array", items: { type: "string", enum: ["queued", "running", "blocked", "completed", "failed", "cancelled"] } } } } } },
  { type: "function", function: { name: "CHUCK_TASK_GET", description: "Read a durable task, including its latest checkpoint and next action.", parameters: { type: "object", properties: { id: { type: "string" } }, required: ["id"] } } },
  { type: "function", function: { name: "CHUCK_TASK_CHECKPOINT", description: "Persist concise progress and the exact next action for a running task. Use after meaningful work and before ending a turn.", parameters: { type: "object", properties: { id: { type: "string" }, checkpoint: { type: "string" }, nextAction: { type: "string" } }, required: ["id", "checkpoint"] } } },
  { type: "function", function: { name: "CHUCK_TASK_BLOCK", description: "Record why an unfinished durable task cannot proceed and what is needed next. Use when a dependency, permission, or decision blocks progress.", parameters: { type: "object", properties: { id: { type: "string" }, reason: { type: "string" }, nextAction: { type: "string" } }, required: ["id", "reason"] } } },
  { type: "function", function: { name: "CHUCK_TASK_COMPLETE", description: "Mark a durable task complete only after its objective is achieved, with a concise result.", parameters: { type: "object", properties: { id: { type: "string" }, result: { type: "string" } }, required: ["id", "result"] } } },
  { type: "function", function: { name: "CHUCK_TASK_CANCEL", description: "Cancel one of the user's unfinished durable tasks.", parameters: { type: "object", properties: { id: { type: "string" } }, required: ["id"] } } },
  { type: "function", function: { name: "CHUCK_TASK_RETRY", description: "Requeue a failed, blocked, or cancelled durable task while preserving its checkpoint.", parameters: { type: "object", properties: { id: { type: "string" } }, required: ["id"] } } },
  { type: "function", function: { name: "CHUCK_TASK_SCHEDULE", description: "Schedule an existing durable task for a future time. Use only when the user explicitly asks Chusky to continue it later.", parameters: { type: "object", properties: { id: { type: "string" }, delaySeconds: { type: "number" }, runAt: { type: "string", description: "Future ISO-8601 timestamp" } }, required: ["id"] } } },
  { type: "function", function: { name: "CHUCK_DAYTONA_WORKSPACE", description: "Create or inspect Chusky's private isolated Daytona computer workspace.", parameters: { type: "object", properties: { action: { type: "string", enum: ["get", "create", "status", "pause", "archive"] } }, required: ["action"] } } },
  { type: "function", function: { name: "CHUCK_DAYTONA_EXECUTE", description: "Run a command in the user's isolated Daytona workspace. Use for code, analysis, and file operations; provide a concise purpose.", parameters: { type: "object", properties: { command: { type: "string" }, cwd: { type: "string" }, timeoutSeconds: { type: "number" }, purpose: { type: "string" } }, required: ["command", "purpose"] } } },
  { type: "function", function: { name: "CHUCK_DAYTONA_LIST_FILES", description: "List files in the user's isolated Daytona workspace.", parameters: { type: "object", properties: { path: { type: "string" }, depth: { type: "number" } } } } },
  { type: "function", function: { name: "CHUCK_DAYTONA_READ_FILE", description: "Read a bounded text file from the user's isolated Daytona workspace.", parameters: { type: "object", properties: { path: { type: "string" }, maxChars: { type: "number" } }, required: ["path"] } } },
  { type: "function", function: { name: "CHUCK_DAYTONA_WRITE_FILE", description: "Write text to a file in the user's isolated Daytona workspace.", parameters: { type: "object", properties: { path: { type: "string" }, content: { type: "string" } }, required: ["path", "content"] } } },
  { type: "function", function: { name: "CHUCK_DAYTONA_FIND_FILES", description: "Find text matches in files in the user's isolated Daytona workspace.", parameters: { type: "object", properties: { path: { type: "string" }, pattern: { type: "string" } }, required: ["pattern"] } } },
  { type: "function", function: { name: "CHUCK_DAYTONA_SEARCH_FILES", description: "Search for files by name pattern in the user's isolated Daytona workspace.", parameters: { type: "object", properties: { path: { type: "string" }, pattern: { type: "string" } }, required: ["pattern"] } } },
  { type: "function", function: { name: "CHUCK_DAYTONA_FILE_DETAILS", description: "Get metadata for a file or directory in the user's isolated Daytona workspace.", parameters: { type: "object", properties: { path: { type: "string" } }, required: ["path"] } } },
  { type: "function", function: { name: "CHUCK_DAYTONA_CREATE_FOLDER", description: "Create a folder in the user's isolated Daytona workspace.", parameters: { type: "object", properties: { path: { type: "string" } }, required: ["path"] } } },
  { type: "function", function: { name: "CHUCK_DAYTONA_MOVE_FILES", description: "Move or rename a file or folder in the user's isolated Daytona workspace.", parameters: { type: "object", properties: { source: { type: "string" }, destination: { type: "string" } }, required: ["source", "destination"] } } },
  { type: "function", function: { name: "CHUCK_DAYTONA_DELETE_FILE", description: "Delete a file or folder from the user's isolated Daytona workspace. Requires confirmation.", parameters: { type: "object", properties: { path: { type: "string" }, recursive: { type: "boolean" } }, required: ["path"] } } },
  { type: "function", function: { name: "CHUCK_DAYTONA_DELETE_WORKSPACE", description: "Permanently delete the user's Daytona workspace and all of its retained state. Requires confirmation.", parameters: { type: "object", properties: {} } } },
  { type: "function", function: { name: "CHUCK_DAYTONA_PREVIEW", description: "Get a temporary preview URL for a web service running on a Daytona workspace port.", parameters: { type: "object", properties: { port: { type: "number" } }, required: ["port"] } } },
  { type: "function", function: { name: "CHUCK_DAYTONA_CREATE_SNAPSHOT", description: "Create a reusable Daytona snapshot of the user's workspace. Requires confirmation.", parameters: { type: "object", properties: { name: { type: "string" } }, required: ["name"] } } },
  { type: "function", function: { name: "CHUCK_DAYTONA_COMPUTER", description: "Operate the user's persistent Daytona desktop. Use accessibility inspection before coordinate actions when possible. Screenshots are returned to the user.", parameters: { type: "object", properties: { action: { type: "string", enum: ["status", "display", "windows", "screenshot", "mouse_move", "mouse_click", "mouse_drag", "mouse_scroll", "keyboard_type", "keyboard_press", "keyboard_hotkey", "accessibility_tree", "accessibility_find", "accessibility_focus", "accessibility_invoke", "accessibility_set_value"] }, x: { type: "number" }, y: { type: "number" }, startX: { type: "number" }, startY: { type: "number" }, endX: { type: "number" }, endY: { type: "number" }, button: { type: "string", enum: ["left", "right", "middle"] }, double: { type: "boolean" }, direction: { type: "string", enum: ["up", "down"] }, amount: { type: "number" }, text: { type: "string" }, delayMs: { type: "number" }, key: { type: "string" }, modifiers: { type: "array", items: { type: "string" } }, keys: { type: "string" }, showCursor: { type: "boolean" }, scope: { type: "string", enum: ["focused", "pid", "all"] }, maxDepth: { type: "number" }, role: { type: "string" }, name: { type: "string" }, nameMatch: { type: "string" }, limit: { type: "number" }, nodeId: { type: "string" }, nodeAction: { type: "string" }, value: { type: "string" } }, required: ["action"] } } },
  { type: "function", function: { name: "CHUCK_DAYTONA_PAUSE", description: "Pause the user's Daytona workspace while preserving its filesystem state.", parameters: { type: "object", properties: {} } } },
  { type: "function", function: { name: "CHUCK_DAYTONA_PTY", description: "Create and control a durable interactive terminal process in the user's Daytona workspace. Use create once, then write/read/status/resize/kill with the returned session ID.", parameters: { type: "object", properties: { action: { type: "string", enum: ["create", "write", "read", "status", "resize", "kill"] }, id: { type: "string" }, input: { type: "string" }, cwd: { type: "string" }, cols: { type: "number" }, rows: { type: "number" } }, required: ["action"] } } },
  { type: "function", function: { name: "CHUCK_DAYTONA_GIT", description: "Use Daytona's Git API for a repository in the isolated workspace. Clone, inspect, branch, pull, stage, commit, and push. Push is externally visible and requires approval.", parameters: { type: "object", properties: { action: { type: "string", enum: ["clone", "status", "branches", "create_branch", "checkout", "pull", "add", "commit", "push"] }, path: { type: "string" }, repoUrl: { type: "string" }, branch: { type: "string" }, files: { type: "array", items: { type: "string" } }, message: { type: "string" }, author: { type: "string" }, email: { type: "string" }, remote: { type: "string" } }, required: ["action"] } } },
  { type: "function", function: { name: "CHUCK_DAYTONA_BROWSER", description: "Browse the web in the user's Daytona desktop through the official Computer Use API. Open http(s) URLs, inspect accessibility snapshots, find elements by role/name, invoke or fill accessible controls, inspect windows, take screenshots, and use keyboard navigation. Verify the page after each interaction. Browser state is retained in the user's Daytona workspace.", parameters: { type: "object", properties: { action: { type: "string", enum: ["status", "open", "snapshot", "find", "focus", "invoke", "fill", "windows", "screenshot", "click", "type", "press", "scroll", "back", "forward", "refresh"] }, url: { type: "string" }, x: { type: "number" }, y: { type: "number" }, text: { type: "string" }, value: { type: "string" }, key: { type: "string" }, keys: { type: "string" }, direction: { type: "string", enum: ["up", "down"] }, amount: { type: "number" }, maxDepth: { type: "number" }, role: { type: "string" }, name: { type: "string" }, nameMatch: { type: "string" }, limit: { type: "number" }, nodeId: { type: "string" }, nodeAction: { type: "string" } }, required: ["action"] } } },
  { type: "function", function: { name: "CHUCK_ARTIFACT", description: "Create and manage durable user-owned deliverables in Daytona. Create text artifacts, register files generated in the workspace, list/get/delete artifacts, and package workspace files into a ZIP. For DOCX, PDF, PPTX, XLSX, images, and videos, generate the valid file in Daytona first, then register its path.", parameters: { type: "object", properties: { action: { type: "string", enum: ["create", "register", "list", "get", "delete", "package"] }, id: { type: "string" }, name: { type: "string" }, type: { type: "string", enum: ["website", "report", "presentation", "pdf", "spreadsheet", "image", "video", "zip", "project"] }, path: { type: "string" }, content: { type: "string" }, contentType: { type: "string" }, files: { type: "array", items: { type: "string" } }, removeFile: { type: "boolean" } }, required: ["action"] } } },
] as const;

/** Validate local-tool arguments at the execution boundary, not just in the model prompt. */
export function validateNativeToolArguments(name: string, args: Record<string, unknown>): void {
  const tool = chuckTools.find((item) => item.function.name === name);
  if (!tool) throw new Error(`Unknown native tool: ${name}`);
  const schema = tool.function.parameters as { required?: readonly string[]; properties?: Record<string, { type?: string; enum?: readonly string[]; items?: { type?: string } }> };
  for (const key of schema.required ?? []) {
    if (!(key in args) || args[key] === undefined || args[key] === null || (typeof args[key] === "string" && !args[key].trim())) throw new Error(`${name} requires argument: ${key}`);
  }
  for (const [key, rule] of Object.entries(schema.properties ?? {})) {
    const value = args[key];
    if (value === undefined || value === null || !rule.type) continue;
    const valid = rule.type === "number" ? typeof value === "number" && Number.isFinite(value)
      : rule.type === "string" ? typeof value === "string"
      : rule.type === "boolean" ? typeof value === "boolean"
      : rule.type === "array" ? Array.isArray(value) && (!rule.items?.type || value.every((item) => typeof item === rule.items?.type))
      : rule.type === "object" ? typeof value === "object" && !Array.isArray(value) : true;
    if (!valid) throw new Error(`${name}.${key} must be a ${rule.type}`);
    if (rule.enum && !rule.enum.includes(value as string)) throw new Error(`${name}.${key} has an unsupported value`);
  }
}
