/** Tools that can read or mutate owner-private state or trigger private actions. */
export const SHARED_CHANNEL_TOOL_DENY = [
  "CHUCK_SAVE_MEMORY", "CHUCK_UPDATE_MEMORY", "CHUCK_SEARCH_MEMORY", "CHUCK_FORGET_MEMORY",
  "CHUCK_TOOL_PREFLIGHT", "CHUCK_INTEGRATION_HEALTH", "CHUCK_ARTIFACT_QA", "CHUCK_FILE_BRIDGE", "CHUCK_MEDIA_BRIDGE", "CHUCK_TOOL_RECOVERY",
  "CHUCK_CREATE_TRIGGER", "CHUCK_LIST_TRIGGER_APPS", "CHUCK_LIST_TRIGGER_TYPES", "CHUCK_LIST_TRIGGERS", "CHUCK_SET_TRIGGER_STATE", "CHUCK_UPDATE_TRIGGER_INSTRUCTIONS", "CHUCK_LIST_CONNECTED_ACCOUNTS",
  "CHUCK_START_PHONE_CALL",
  "CHUCK_TREG_SEARCH", "CHUCK_TREG_GET", "CHUCK_TREG_PLATFORMS", "CHUCK_TREG_MY_TOOLS", "CHUCK_TREG_CALL", "CHUCK_TREG_ENRICH_PERSON", "CHUCK_TREG_ENRICH_COMPANY", "CHUCK_TREG_RESOLVE", "CHUCK_TREG_BALANCE", "CHUCK_TREG_USAGE", "CHUCK_TREG_OAUTH_START", "CHUCK_TREG_OAUTH_STATUS", "CHUCK_TREG_OAUTH_CONNECTIONS", "CHUCK_TREG_OAUTH_REVOKE",
  "CHUCK_TINYFISH_RESEARCH", "CHUCK_TINYFISH_MONITOR",
  "CHUCK_SCRATCHPAD_READ", "CHUCK_SCRATCHPAD_WRITE", "CHUCK_SCRATCHPAD_CLEAR",
  "CHUCK_CONTEXT_SEARCH", "CHUCK_CONTEXT_SAVE", "CHUCK_AUTONOMY_STATUS", "CHUCK_AUTONOMY_RECONCILE", "CHUCK_AUTONOMY_PLAYBOOK",
  "CHUCK_SAVE_IMAGE_ASSET", "CHUCK_SEARCH_IMAGE_ASSETS", "CHUCK_GET_IMAGE_ASSET", "CHUCK_FORGET_IMAGE_ASSET",
  "CHUCK_DAYTONA_IMAGE",
  "CHUCK_VAULT_SAVE", "CHUCK_VAULT_LIST", "CHUCK_VAULT_STATUS", "CHUCK_VAULT_LOGIN", "CHUCK_VAULT_LOGOUT",
  "CHUCK_LINK_CONNECT", "CHUCK_LINK_STATUS", "CHUCK_LINK_WALLET_CONNECT", "CHUCK_LINK_WALLET_STATUS", "CHUCK_LINK_PAYMENT_METHODS", "CHUCK_LINK_CREATE_SPEND_REQUEST", "CHUCK_LINK_INSPECT_CHECKOUT", "CHUCK_LINK_MPP_DISCOVER", "CHUCK_LINK_MPP_PAY", "CHUCK_LINK_UCP_SEARCH", "CHUCK_LINK_UCP_CREATE_CHECKOUT", "CHUCK_LINK_UCP_COMPLETE_CHECKOUT", "CHUCK_LINK_CONFIRM_ORDER", "CHUCK_LINK_WAIT_FOR_APPROVAL", "CHUCK_LINK_EXECUTE_PAYMENT", "CHUCK_LINK_RECEIPT", "CHUCK_LINK_REPORT_OUTCOME", "CHUCK_LINK_SPEND_STATUS", "CHUCK_LINK_SPEND_LIST", "CHUCK_LINK_SPEND_CANCEL", "CHUCK_LINK_COMPLETE_CHECKOUT", "CHUCK_LINK_WALLET_DISCONNECT",
  "CHUCK_BROWSER", "CHUCK_DAYTONA_COMPUTER", "CHUCK_BROWSER_PLAN", "CHUCK_BROWSER_NEXT", "CHUCK_BROWSER_SESSION_HEALTH", "CHUCK_BROWSER_SESSION_REVOKE", "CHUCK_BROWSER_PLAYBOOK_SAVE", "CHUCK_BROWSER_PLAYBOOK_LIST", "CHUCK_BROWSER_PLAYBOOK_REMOVE", "CHUCK_BROWSER_VERIFY", "CHUCK_BROWSER_AUDIT_LIST",
  "CHUCK_BROWSER_HANDOFF", "CHUCK_BROWSER_HANDOFF_STATUS", "CHUCK_BROWSER_HANDOFF_COMPLETE",
  "CHUCK_SHOPPING_START", "CHUCK_SHOPPING_LIST", "CHUCK_SHOPPING_SELECT_RETAILER", "CHUCK_SHOPPING_UPDATE",
  "CHUCK_SHOPPING_CANCEL", "CHUCK_SHOPPING_PAUSE", "CHUCK_SHOPPING_RESUME", "CHUCK_SHOPPING_SAVE_SITE",
  "CHUCK_SHOPPING_LIST_SITES", "CHUCK_SHOPPING_REMOVE_SITE",
] as const;

const sharedChannelDeniedTools = new Set<string>(SHARED_CHANNEL_TOOL_DENY);

export function isSharedChannelToolDenied(slug: string): boolean {
  const canonical = slug;
  return sharedChannelDeniedTools.has(canonical);
}
